import json
import sys
sys.path.append("/home/linuxlite/.gemini/antigravity/scratch/raahiyoo/scripts")

from populate_massive_destinations import destinations_db

# 35 more iconic destinations to add
additional_destinations = [
  # --- GUJARAT & RAJASTHAN ---
  {
    "id": "rani-ki-vav",
    "name": "Rani Ki Vav & Modhera Sun Temple",
    "state": "Gujarat",
    "region": "west",
    "tagline": "UNESCO 7-Story Inverted Stepwell & Sun Temple",
    "description": "An architectural marvel in Patan. An inverted subterranean stepwell temple with 7 levels and over 500 sculpted avatars of Vishnu, paired with the 11th-century Modhera Sun Temple.",
    "elevation": "76 m (249 ft)",
    "bestTime": "Oct to Mar",
    "idealDays": "1 - 2 Days",
    "category": "heritage",
    "mood": ["Heritage", "Architecture", "Wonder"],
    "basePriceINR": 2400,
    "rating": 4.8,
    "reviewsCount": 310,
    "heroImage": "https://images.unsplash.com/photo-1600100397608-f010e47f985a?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Rani Ki Vav", "Modhera Sun Temple", "Patan Patola", "UNESCO Stepwell"],
    "highlights": ["7-story subterranean stepwell with 500+ intricate Vishnu sculptures", "Modhera Sun Temple with 108 miniature shrines around Surya Kund", "Patan traditional double-ikat Patola silk weaving demo"],
    "nearestHubs": { "airport": "Ahmedabad Airport AMD (115 km)", "railway": "Mehsana Junction (35 km)", "road": "State Highway 7 via Mehsana" },
    "transitSummary": "115 km (2 hours) from Ahmedabad Airport via smooth 4-lane state highway."
  },
  {
    "id": "saputara",
    "name": "Saputara Hill Station",
    "state": "Gujarat",
    "region": "west",
    "tagline": "Gujarat's Only Hill Station in Sahyadri Dang Forests",
    "description": "Perched at 3,000 ft in the lush Dang tribal forest. Enjoy pedal boating on Saputara Lake, the Pushpak ropeway cable car, Gira waterfalls, and tribal museum.",
    "elevation": "875 m (2,870 ft)",
    "bestTime": "Jul to Mar (Monsoon & Winter)",
    "idealDays": "2 Days",
    "category": "mountains",
    "mood": ["Nature", "Monsoon", "Family"],
    "basePriceINR": 2500,
    "rating": 4.6,
    "reviewsCount": 240,
    "heroImage": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Saputara Lake", "Pushpak Ropeway", "Gira Falls", "Dang Forests"],
    "highlights": ["Pushpak Ropeway gliding over Saputara Lake valley", "Gira Waterfalls 75-ft roaring cascade in monsoon", "Governor's Hill sunset viewpoint overlooking Khandesh plains"],
    "nearestHubs": { "airport": "Surat Airport STV (160 km) / Nashik (80 km)", "railway": "Bilimora / Nashik Road (80 km)", "road": "Nashik-Saputara Ghat Road" },
    "transitSummary": "80 km from Nashik or 160 km from Surat via picturesque forested ghat roads."
  },
  {
    "id": "kumbhalgarh",
    "name": "Kumbhalgarh (Great Wall of India)",
    "state": "Rajasthan",
    "region": "west",
    "tagline": "World's 2nd Longest Continuous Wall (36 km)",
    "description": "A massive Mewar fortress built by Rana Kumbha atop the Aravalis. Features a 36-km fortified perimeter wall — second only to the Great Wall of China — with 360 ancient temples inside.",
    "elevation": "1,100 m (3,600 ft)",
    "bestTime": "Oct to Mar",
    "idealDays": "1 - 2 Days",
    "category": "heritage",
    "mood": ["Heritage", "Wonder", "History"],
    "basePriceINR": 2800,
    "rating": 4.8,
    "reviewsCount": 350,
    "heroImage": "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Great Wall of India", "Badal Mahal", "UNESCO Fort", "Rana Kumbha"],
    "highlights": ["Walking along the 36-km colossal rampart wall where 8 horses could ride abreast", "Badal Mahal (Palace of Clouds) top-floor view over Marwar desert and Mewar hills", "Evening Sound & Light show illuminating the entire mountain fortress"],
    "nearestHubs": { "airport": "Udaipur Airport (100 km)", "railway": "Falna (80 km) / Udaipur", "road": "Udaipur-Kumbhalgarh Road" },
    "transitSummary": "100 km (2.5 hours) scenic mountain drive from Udaipur."
  },
  {
    "id": "bikaner",
    "name": "Bikaner & Junagarh Fort",
    "state": "Rajasthan",
    "region": "west",
    "tagline": "Camel Country, Unconquered Fort & Karni Mata Temple",
    "description": "Surrounded by Thar desert dunes. Discover the unconquered Junagarh Fort, the royal Lalgarh Palace, ICAR National Research Centre on Camel, and the sacred Karni Mata (Rat) Temple in Deshnoke.",
    "elevation": "242 m (794 ft)",
    "bestTime": "Oct to Mar",
    "idealDays": "2 Days",
    "category": "heritage",
    "mood": ["Heritage", "Food", "Culture"],
    "basePriceINR": 2500,
    "rating": 4.7,
    "reviewsCount": 290,
    "heroImage": "https://images.unsplash.com/photo-1577717903315-1691ae25ab3f?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Junagarh Fort", "Karni Mata Temple", "Camel Breeding Farm", "Bikaneri Bhujia"],
    "highlights": ["Junagarh Fort with gold leaf Anup Mahal and Badal Mahal blue cloud walls", "Karni Mata Temple housing 25,000 sacred black and white rats", "Tasting fresh camel milk kulfi and world-famous Bikaneri Bhujia"],
    "nearestHubs": { "airport": "Bikaner Airport BKB / Jodhpur (250 km)", "railway": "Bikaner Junction BKN", "road": "Amritsar-Jamnagar Expressway (NE-5)" },
    "transitSummary": "Direct flights from Delhi to Bikaner (BKB) or direct express trains from Delhi and Jaipur."
  },

  # --- MAHARASHTRA & CENTRAL INDIA ---
  {
    "id": "tadoba",
    "name": "Tadoba Andhari Tiger Reserve",
    "state": "Maharashtra",
    "region": "west",
    "tagline": "The Real Land of Tigers & Bamboo Safaris",
    "description": "Maharashtra's oldest and largest national park, renowned for having India's highest tiger sighting probabilities across Moharli, Kolara, and Navegaon safari zones.",
    "elevation": "200 m (656 ft)",
    "bestTime": "Oct to Jun",
    "idealDays": "2 - 3 Days",
    "category": "heritage",
    "mood": ["Wildlife", "Safari", "Adventure"],
    "basePriceINR": 3600,
    "rating": 4.9,
    "reviewsCount": 380,
    "heroImage": "https://images.unsplash.com/photo-1577717903315-1691ae25ab3f?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Tiger Safari", "Moharli Zone", "Tadoba Lake", "Bamboo Forest"],
    "highlights": ["Unrivaled Royal Bengal Tiger sightings on open 4x4 Gypsy safaris", "Tadoba Lake with mugger crocodiles and water birds", "Night safari in buffer zones spotting leopards and sloth bears"],
    "nearestHubs": { "airport": "Dr. Babasaheb Ambedkar Airport Nagpur NAG (140 km)", "railway": "Chandrapur CD (45 km) / Nagpur", "road": "Nagpur-Chandrapur Highway" },
    "transitSummary": "140 km (3 hours) from Nagpur International Airport via 4-lane highway."
  },
  {
    "id": "kaas-plateau",
    "name": "Kaas Plateau (Satara)",
    "state": "Maharashtra",
    "region": "west",
    "tagline": "UNESCO Valley of Flowers of the Western Ghats",
    "description": "A volcanic laterite plateau near Satara that transforms into a vibrant carpet of 850 species of wild flowering plants, orchids, and insectivorous drosera during post-monsoon.",
    "elevation": "1,200 m (3,937 ft)",
    "bestTime": "Aug to Oct (Peak Blooms)",
    "idealDays": "1 - 2 Days",
    "category": "mountains",
    "mood": ["Nature", "Photography", "Monsoon"],
    "basePriceINR": 2400,
    "rating": 4.8,
    "reviewsCount": 330,
    "heroImage": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Valley of Flowers", "UNESCO Plateau", "Kaas Lake", "Thoseghar Falls"],
    "highlights": ["Walking along floral carpets of blue Utricularia, purple Pogostemon, and yellow Smithia", "Kaas Lake scenic boating and dense evergreen forests", "Thoseghar 1,000-ft cascading monsoon waterfalls nearby"],
    "nearestHubs": { "airport": "Pune Airport PNQ (140 km)", "railway": "Satara (STR) (25 km)", "road": "Satara-Kaas Road" },
    "transitSummary": "25 km uphill from Satara or 140 km (3 hours) from Pune Airport via NH-48."
  },
  {
    "id": "bhandardara",
    "name": "Bhandardara & Arthur Lake",
    "state": "Maharashtra",
    "region": "west",
    "tagline": "Fireflies Festival, Umbrella Falls & Kalsubai Peak",
    "description": "A serene Sahyadri mountain resort on the Pravara River. Base for trekking Kalsubai (1,646 m) — highest peak of Maharashtra — Arthur Lake camping, and the glowing monsoon Fireflies Festival.",
    "elevation": "740 m (2,427 ft)",
    "bestTime": "Jun to Feb (May-Jun for Fireflies)",
    "idealDays": "2 Days",
    "category": "mountains",
    "mood": ["Monsoon", "High Treks", "Offbeat"],
    "basePriceINR": 2500,
    "rating": 4.7,
    "reviewsCount": 260,
    "heroImage": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Kalsubai Peak", "Fireflies Festival", "Arthur Lake", "Umbrella Falls"],
    "highlights": ["Trek to Kalsubai Peak (5,400 ft) Everest of Maharashtra", "Millions of glowing fireflies synchronizing on trees in pre-monsoon", "Wilson Dam (1910 AD) & Umbrella Falls cascade"],
    "nearestHubs": { "airport": "Nashik Airport (80 km) / Mumbai (165 km)", "railway": "Igatpuri IGP (45 km)", "road": "Mumbai-Nashik Expressway" },
    "transitSummary": "45 km from Igatpuri Railway Station on the Mumbai-Nashik corridor."
  },
  {
    "id": "bandhavgarh",
    "name": "Bandhavgarh National Park",
    "state": "Madhya Pradesh",
    "region": "central",
    "tagline": "World's Highest Royal Bengal Tiger Density",
    "description": "Surrounded by 32 hills and sal forests with the ancient 2,000-year-old Bandhavgarh Fort and reclining Shesh Shaiya Vishnu statue. Renowned for legendary tiger lineages in Tala zone.",
    "elevation": "440 m (1,440 ft)",
    "bestTime": "Oct to Jun",
    "idealDays": "2 - 3 Days",
    "category": "heritage",
    "mood": ["Wildlife", "Safari", "Adventure"],
    "basePriceINR": 3800,
    "rating": 4.9,
    "reviewsCount": 420,
    "heroImage": "https://images.unsplash.com/photo-1577717903315-1691ae25ab3f?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Highest Tiger Density", "Tala Zone", "Shesh Shaiya", "Bandhavgarh Fort"],
    "highlights": ["Highest tiger sighting hit-rate in India across Tala and Magdhi zones", "Shesh Shaiya 35-ft 10th-century reclining Vishnu stone statue beside natural spring", "Ancient hill fort ruins and caves with Brahmi inscriptions"],
    "nearestHubs": { "airport": "Jabalpur Airport JLR (165 km)", "railway": "Umaria UMR (32 km) / Katni (95 km)", "road": "Jabalpur-Katni-Umaria Highway" },
    "transitSummary": "165 km (3.5 hours) from Jabalpur Airport or 32 km from Umaria Railway Station."
  },
  {
    "id": "kanha",
    "name": "Kanha Tiger Reserve",
    "state": "Madhya Pradesh",
    "region": "central",
    "tagline": "Rudyard Kipling's Jungle Book & Barasingha Swamp Deer",
    "description": "The lush sal and bamboo meadows that inspired 'The Jungle Book'. Famous for bringing the endangered Hardground Barasingha back from extinction and thrilling tiger safaris.",
    "elevation": "600 m (1,970 ft)",
    "bestTime": "Oct to Jun",
    "idealDays": "2 - 3 Days",
    "category": "heritage",
    "mood": ["Wildlife", "Nature", "Safari"],
    "basePriceINR": 3700,
    "rating": 4.9,
    "reviewsCount": 390,
    "heroImage": "https://images.unsplash.com/photo-1577717903315-1691ae25ab3f?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Jungle Book", "Barasingha", "Mukki Zone", "Sal Meadows"],
    "highlights": ["Expansive open grasslands with grazing herds of Barasingha (Swamp Deer)", "Bamni Dadar (Sunset Point) watching raptors soar over the canopy", "Jungle Book tribal museum and naturalist-guided tracking"],
    "nearestHubs": { "airport": "Jabalpur (160 km) / Raipur (210 km)", "railway": "Gondia / Jabalpur", "road": "Jabalpur-Mandla-Kanha Highway" },
    "transitSummary": "160 km (3.5 hours) from Jabalpur Airport via Mandla."
  },
  {
    "id": "gwalior-orchha",
    "name": "Gwalior Fort & Orchha",
    "state": "Madhya Pradesh",
    "region": "central",
    "tagline": "The Pearl in the Fort Necklace & Palaces of Betwa",
    "description": "Described by Mughal Emperor Babur as the pearl among fortresses in India. Experience Gwalior Fort's turquoise-tiled Man Mandir Palace, the royal Scindia Jai Vilas Palace, and Orchha's riverside cenotaphs on the Betwa River.",
    "elevation": "211 m (692 ft)",
    "bestTime": "Oct to Mar",
    "idealDays": "2 - 3 Days",
    "category": "heritage",
    "mood": ["Heritage", "Royal", "History"],
    "basePriceINR": 2700,
    "rating": 4.8,
    "reviewsCount": 410,
    "heroImage": "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Gwalior Fort", "Man Mandir", "Orchha Chhatris", "Betwa River"],
    "highlights": ["Gwalior Fort 8th-century clifftop fortress with blue glazed tile murals", "Jai Vilas Palace Durbar Hall with two 3.5-ton crystal chandeliers and silver train", "Orchha 16th-century Bundela royal cenotaphs (Chhatris) reflecting in Betwa River"],
    "nearestHubs": { "airport": "Gwalior Rajmata Vijaya Raje Scindia Airport GWL", "railway": "Gwalior Junction GWL / Jhansi JHS", "road": "North-South Corridor (NH-44)" },
    "transitSummary": "Direct flights to Gwalior (GWL). Direct Vande Bharat and Shatabdi from Delhi in ~3 hours."
  },

  # --- KARNATAKA & KERALA & TAMIL NADU ---
  {
    "id": "dandeli",
    "name": "Dandeli & Kali River",
    "state": "Karnataka",
    "region": "south",
    "tagline": "White Water Rafting & Hornbill Jungle Canopy",
    "description": "South India's adventure capital on the roaring Kali River. Experience thrilling grade 3 white water rafting, kayaking, natural jacuzzi baths, and hornbill birdwatching in dense Western Ghats.",
    "elevation": "473 m (1,552 ft)",
    "bestTime": "Oct to May",
    "idealDays": "2 - 3 Days",
    "category": "mountains",
    "mood": ["Adventure", "Rafting", "Wildlife"],
    "basePriceINR": 2800,
    "rating": 4.8,
    "reviewsCount": 350,
    "heroImage": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Kali River Rafting", "Hornbill Spotting", "Syntheri Rocks", "Jungle Camp"],
    "highlights": ["12-km white water rafting through grade 3 rapids on Kali River", "Syntheri Rocks 300-ft monolithic granite canyon and Kaner River waterfall", "Coracle ride through crocodile habitats and natural jacuzzi rapids"],
    "nearestHubs": { "airport": "Hubli Airport HBX (75 km) / Goa (135 km)", "railway": "Alnavar Junction (32 km) / Londa", "road": "Hubli-Dharwad-Dandeli Road" },
    "transitSummary": "75 km (1.5 hours) from Hubli Airport or 135 km from Goa."
  },
  {
    "id": "kabini",
    "name": "Kabini & Nagarhole",
    "state": "Karnataka",
    "region": "south",
    "tagline": "The Land of the Black Panther & River Safaris",
    "description": "World-famous for sightings of 'Saya' the legendary Black Panther and India's largest congregation of Asian elephants along the banks of the Kabini River in Nagarhole Tiger Reserve.",
    "elevation": "700 m (2,296 ft)",
    "bestTime": "Oct to May",
    "idealDays": "2 - 3 Days",
    "category": "heritage",
    "mood": ["Wildlife", "Safari", "Luxury"],
    "basePriceINR": 4600,
    "rating": 4.9,
    "reviewsCount": 370,
    "heroImage": "https://images.unsplash.com/photo-1577717903315-1691ae25ab3f?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Black Panther", "Kabini Boat Safari", "Nagarhole", "Elephant Herds"],
    "highlights": ["Evening boat safari on Kabini reservoir watching 50+ wild elephants gather", "Tracking leopards and the melanistic Black Panther on 4x4 Jeep safaris", "Luxury riverside wildlife lodges with coracle rides"],
    "nearestHubs": { "airport": "Mysuru Airport (75 km) / Bengaluru (220 km)", "railway": "Mysuru Junction MYS (75 km)", "road": "Mysuru-HD Kote-Kabini Road" },
    "transitSummary": "75 km (1.5 hours) from Mysuru or 4.5 hours from Bengaluru."
  },
  {
    "id": "badami-pattadakal",
    "name": "Badami Caves & Pattadakal",
    "state": "Karnataka",
    "region": "south",
    "tagline": "6th-Century Chalukya Rock-Cut Caves & Agastya Lake",
    "description": "Carved into red sandstone cliffs overlooking the emerald Agastya Lake. Experience 4 monumental rock-cut cave temples in Badami and the UNESCO temple fusion complex at Pattadakal.",
    "elevation": "586 m (1,922 ft)",
    "bestTime": "Oct to Mar",
    "idealDays": "2 Days",
    "category": "heritage",
    "mood": ["Heritage", "Art", "Architecture"],
    "basePriceINR": 2400,
    "rating": 4.8,
    "reviewsCount": 290,
    "heroImage": "https://images.unsplash.com/photo-1600100397608-f010e47f985a?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Badami Caves", "Agastya Lake", "Pattadakal UNESCO", "Chalukya"],
    "highlights": ["Cave 1 18-armed dancing Nataraja with 81 dancing postures", "Bhutanatha Temple standing serene at the edge of Agastya Lake", "Pattadakal 7th-century UNESCO fusion of Dravidian and Nagara temple architecture"],
    "nearestHubs": { "airport": "Hubli Airport HBX (105 km)", "railway": "Badami (BDM)", "road": "Hubli-Bagalkot Road" },
    "transitSummary": "105 km (2 hours) from Hubli Airport. Direct trains stop at Badami Railway Station."
  },
  {
    "id": "murudeshwar",
    "name": "Murudeshwar & Netrani Island",
    "state": "Karnataka",
    "region": "south",
    "tagline": "World's 2nd Tallest Shiva Statue & Scuba Diving",
    "description": "Surrounded on three sides by the Arabian Sea. Marvel at the 123-ft giant seated Lord Shiva statue, the 20-story Rajagopuram with elevator lift, and scuba dive at Netrani Coral Island.",
    "elevation": "Sea Level",
    "bestTime": "Oct to Apr",
    "idealDays": "2 Days",
    "category": "sacred",
    "mood": ["Spiritual", "Beaches", "Diving"],
    "basePriceINR": 2600,
    "rating": 4.8,
    "reviewsCount": 390,
    "heroImage": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Giant Shiva Statue", "Rajagopuram", "Netrani Scuba Diving", "Arabian Sea"],
    "highlights": ["Elevator ride to the 18th floor of the 249-ft Rajagopuram for 360-degree sea view", "123-ft towering Lord Shiva statue on Kanduka Hill cliff", "Boat trip to Netrani (Pigeon) Island for scuba diving and coral snorkeling"],
    "nearestHubs": { "airport": "Mangalore Airport IXE (155 km) / Goa (180 km)", "railway": "Murdeshwar (MRDW)", "road": "NH-66 Coastal Highway" },
    "transitSummary": "Direct trains stop at Murdeshwar (MRDW) on the Konkan Railway network."
  },
  {
    "id": "athirappilly",
    "name": "Athirappilly & Vazhachal Falls",
    "state": "Kerala",
    "region": "south",
    "tagline": "The Niagara of South India & Bahubali Waterfalls",
    "description": "Kerala's largest waterfall, plunging 80 ft across a 330-ft wide horseshoe cliff on the Chalakudy River. Made world-famous as the filming location for the blockbuster movie 'Bahubali'.",
    "elevation": "130 m (426 ft)",
    "bestTime": "Jun to Jan (Monsoon for Peak Roar)",
    "idealDays": "1 - 2 Days",
    "category": "mountains",
    "mood": ["Waterfalls", "Nature", "Monsoon"],
    "basePriceINR": 2700,
    "rating": 4.8,
    "reviewsCount": 340,
    "heroImage": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Niagara of South India", "Bahubali Waterfall", "Chalakudy River", "Vazhachal"],
    "highlights": ["Trek down to the mist-soaked base of the 80-ft roaring Athirappilly falls", "Vazhachal cascading river rapids and herbal gardens", "Sholayar rainforest canopy drive spotting Great Indian Hornbills"],
    "nearestHubs": { "airport": "Cochin International Airport COK (40 km)", "railway": "Chalakudi CKI (30 km)", "road": "Chalakudy-Anamala Road (SH-21)" },
    "transitSummary": "40 km (1 hour) smooth drive from Kochi International Airport (COK)."
  },
  {
    "id": "bekal-fort",
    "name": "Bekal Fort & Coastal Beach",
    "state": "Kerala",
    "region": "south",
    "tagline": "Largest Keyhole Sea Fort in Kerala & Waves",
    "description": "Spanning 40 acres into the Arabian Sea in Kasaragod. Famous for its keyhole-shaped ramparts rising straight from the beach, observation tower, and dramatic wave splashes.",
    "elevation": "Sea Level",
    "bestTime": "Oct to Mar",
    "idealDays": "2 Days",
    "category": "beaches",
    "mood": ["Beaches", "Heritage", "Photography"],
    "basePriceINR": 2800,
    "rating": 4.7,
    "reviewsCount": 270,
    "heroImage": "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Bekal Fort", "Observation Tower", "Keyhole Fort", "Arabian Sea Waves"],
    "highlights": ["Walking along massive laterite sea bastions with waves crashing below", "Central observation tower offering 360-degree Arabian Sea and coastline vista", "Illuminated evening beach walkway around the fort walls"],
    "nearestHubs": { "airport": "Mangalore Airport IXE (65 km) / Kannur (85 km)", "railway": "Kasaragod (16 km) / Kanhangad", "road": "NH-66 Coastal Highway" },
    "transitSummary": "65 km (1.5 hours) from Mangalore Airport via NH-66."
  },
  {
    "id": "mahabalipuram",
    "name": "Mahabalipuram (Shore Temple)",
    "state": "Tamil Nadu",
    "region": "south",
    "tagline": "UNESCO 7th-Century Shore Temple & Pancha Rathas",
    "description": "An ancient Pallava port city on the Bay of Bengal. Famous for the 8th-century Shore Temple battered by ocean waves, monolithic Pancha Rathas (chariots), and Arjuna's Penance rock relief.",
    "elevation": "Sea Level",
    "bestTime": "Oct to Mar",
    "idealDays": "1 - 2 Days",
    "category": "heritage",
    "mood": ["Heritage", "Ocean", "Architecture"],
    "basePriceINR": 2600,
    "rating": 4.8,
    "reviewsCount": 420,
    "heroImage": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Shore Temple", "Pancha Rathas", "Arjunas Penance", "Krishna Butter Ball"],
    "highlights": ["UNESCO Shore Temple standing on the edge of the Bay of Bengal", "Pancha Rathas 5 monolithic monolithic temples carved from single granite boulders", "Krishna's Butter Ball 250-ton giant boulder balancing on a 45-degree slope"],
    "nearestHubs": { "airport": "Chennai International Airport MAA (55 km)", "railway": "Chengalpattu CGL (30 km) / Chennai", "road": "East Coast Road (ECR)" },
    "transitSummary": "55 km (1 hour) scenic drive from Chennai Airport along the 4-lane East Coast Road."
  },
  {
    "id": "coonoor",
    "name": "Coonoor & Sim's Park",
    "state": "Tamil Nadu",
    "region": "south",
    "tagline": "Tranquil Nilgiri Tea Valleys & Dolphin's Nose",
    "description": "The quieter, romantic sister of Ooty nestled at 6,000 ft. Ride the Nilgiri Toy Train over deep ravines, visit Sim's Park botanical garden, and take in the sheer drop view at Dolphin's Nose viewpoint.",
    "elevation": "1,850 m (6,070 ft)",
    "bestTime": "Year-round",
    "idealDays": "2 Days",
    "category": "mountains",
    "mood": ["Tea Hills", "Romantic", "Nature"],
    "basePriceINR": 2900,
    "rating": 4.7,
    "reviewsCount": 310,
    "heroImage": "https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Sims Park", "Dolphins Nose", "Nilgiri Toy Train", "Highfield Tea"],
    "highlights": ["Dolphin's Nose viewpoint overlooking Catherine Falls and Nilgiri canyons", "Sim's Park 12-hectare botanical garden with rare temperate trees", "Highfield Tea Factory estate walking tour"],
    "nearestHubs": { "airport": "Coimbatore Airport (70 km)", "railway": "Coonoor ONR (Nilgiri Toy Train)", "road": "Mettupalayam-Coonoor Ghat Road" },
    "transitSummary": "70 km (2 hours) from Coimbatore Airport via Mettupalayam ghat road."
  },

  # --- EAST & NORTHEAST & ISLANDS ---
  {
    "id": "shantiniketan",
    "name": "Shantiniketan (Visva-Bharati)",
    "state": "West Bengal",
    "region": "east",
    "tagline": "UNESCO Abode of Peace & Tagore's Open-Air University",
    "description": "Nobel Laureate Rabindranath Tagore's utopian open-air university. Experience classes under banyan trees, the vibrant Saturday Sonajhurir Haat tribal craft market, and Poush Mela folk music.",
    "elevation": "56 m (184 ft)",
    "bestTime": "Oct to Mar (Dec for Poush Mela)",
    "idealDays": "2 Days",
    "category": "heritage",
    "mood": ["Culture", "Art", "Peace"],
    "basePriceINR": 2200,
    "rating": 4.8,
    "reviewsCount": 280,
    "heroImage": "https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Visva Bharati", "Rabindranath Tagore", "Sonajhurir Haat", "Baul Music"],
    "highlights": ["Tagore's Ashram and Uttarayan complex five heritage residences", "Saturday Sonajhurir Haat tribal handicrafts and live Baul music under sal trees", "Kala Bhavana fine arts mural exhibits"],
    "nearestHubs": { "airport": "Kolkata Airport (160 km) / Durgapur (60 km)", "railway": "Bolpur Shantiniketan (BHP)", "road": "NH-19 via Panagarh" },
    "transitSummary": "2-hour train ride from Kolkata (Howrah/Sealdah) to Bolpur Shantiniketan (BHP)."
  },
  {
    "id": "netarhat",
    "name": "Netarhat (Queen of Chotanagpur)",
    "state": "Jharkhand",
    "region": "east",
    "tagline": "Sunrise Over Pine Forests & Magnolia Sunset Point",
    "description": "Perched at 3,600 ft atop the Chotanagpur plateau surrounded by thick sal and deodar forests. Famous for breath-stopping sunrise from Netarhat Dam and sunset from Magnolia Point.",
    "elevation": "1,100 m (3,600 ft)",
    "bestTime": "Oct to Apr",
    "idealDays": "2 Days",
    "category": "mountains",
    "mood": ["Offbeat", "Nature", "Peace"],
    "basePriceINR": 2100,
    "rating": 4.7,
    "reviewsCount": 220,
    "heroImage": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Queen of Chotanagpur", "Magnolia Point", "Upper Ghaghri Falls", "Pine Forest"],
    "highlights": ["Magnolia Point romantic sunset over Vindhya valley horizons", "Upper Ghaghri and Lower Ghaghri forest waterfalls", "Netarhat Residential School campus and pine woods walk"],
    "nearestHubs": { "airport": "Birsa Munda Airport Ranchi IXR (155 km)", "railway": "Ranchi (155 km) / Tori", "road": "Ranchi-Lohardaga-Netarhat Road" },
    "transitSummary": "155 km (3.5 hours) scenic drive through tribal forests from Ranchi Airport."
  },
  {
    "id": "mainpat",
    "name": "Mainpat (Shimla of Chhattisgarh)",
    "state": "Chhattisgarh",
    "region": "central",
    "tagline": "Tibetan Monastery, Bouncing Land & Tiger Point Falls",
    "description": "A lush green plateau at 3,600 ft in Surguja. Home to a vibrant Tibetan refugee settlement, Dhakpo Shedrupling Monastery, Tiger Point falls, and the mysterious Jaljali (bouncing earth).",
    "elevation": "1,100 m (3,600 ft)",
    "bestTime": "Oct to Mar",
    "idealDays": "2 Days",
    "category": "mountains",
    "mood": ["Offbeat", "Culture", "Waterfalls"],
    "basePriceINR": 2300,
    "rating": 4.7,
    "reviewsCount": 190,
    "heroImage": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Shimla of Chhattisgarh", "Jaljali Bouncing Land", "Tiger Point", "Tibetan Monastery"],
    "highlights": ["Jaljali unique natural trampoline-like spongy bouncing land", "Dhakpo Shedrupling Tibetan Buddhist Monastery and prayer wheels", "Tiger Point 60-ft waterfall plunging into dense sal forest canyon"],
    "nearestHubs": { "airport": "Raipur Airport (360 km) / Ranchi (280 km)", "railway": "Ambikapur ABKP (50 km)", "road": "Ambikapur-Mainpat Road" },
    "transitSummary": "50 km (1.2 hours) from Ambikapur Railway Station via ghat road."
  },
  {
    "id": "mechuka",
    "name": "Mechuka Valley",
    "state": "Arunachal Pradesh",
    "region": "northeast",
    "tagline": "The Forbidden Fairytale Valley of Yarlung Tsangpo",
    "description": "An untouched paradise near the Tibet border in West Siang at 6,000 ft. Surrounded by snow-dusted peaks, the emerald Yargyapchu River, wooden hanging bridges, and the 400-year-old Samten Yongcha Gompa.",
    "elevation": "1,829 m (6,000 ft)",
    "bestTime": "Oct to Apr",
    "idealDays": "4 - 5 Days",
    "category": "mountains",
    "mood": ["High Treks", "Offbeat", "Adventure"],
    "basePriceINR": 3400,
    "rating": 4.9,
    "reviewsCount": 180,
    "heroImage": "https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Mechuka Valley", "Memba Tribe", "Hanging Bridge", "Samten Gompa"],
    "highlights": ["400-year-old Samten Yongcha clifftop monastery", "Walking across traditional wooden cane suspension bridges over crystal rivers", "Traditional wooden homestay hospitality with Memba tribe"],
    "nearestHubs": { "airport": "Dibrugarh Airport DBR (380 km) / Pasighat (280 km)", "railway": "Murkongselek / Silapathar", "road": "Aalo-Mechuka Mountain Road" },
    "transitSummary": "Drive from Dibrugarh/Pasighat via Along (Aalo) to Mechuka. Inner Line Permit (ILP) required."
  },
  {
    "id": "unakoti",
    "name": "Unakoti Rock Sculptures",
    "state": "Tripura",
    "region": "northeast",
    "tagline": "One Less Than a Crore Shaivite Rock Carvings",
    "description": "An extraordinary 8th-century archaeological treasure hidden in lush forested hills. Marvel at the colossal 30-ft bas-relief face of Lord Shiva (Unakotiswara Kal Bhairava) carved directly into living rock.",
    "elevation": "120 m (394 ft)",
    "bestTime": "Oct to Mar (Apr for Ashokastami Mela)",
    "idealDays": "1 - 2 Days",
    "category": "heritage",
    "mood": ["Heritage", "Wonder", "Offbeat"],
    "basePriceINR": 2300,
    "rating": 4.8,
    "reviewsCount": 210,
    "heroImage": "https://images.unsplash.com/photo-1600100397608-f010e47f985a?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Unakoti", "Shiva Rock Relief", "Angkor Wat of India", "Tripura"],
    "highlights": ["30-ft monumental head of Lord Shiva carved into a mountain rockface", "Natural stream waterfalls flowing over ancient rock-carved deities", "Ganesh Kund natural holy pool and stone relief figures"],
    "nearestHubs": { "airport": "Maharaja Bir Bikram Airport Agartala IXA (175 km)", "railway": "Kumarghat (20 km) / Dharmanagar", "road": "Agartala-Kailashahar Highway" },
    "transitSummary": "20 km from Kumarghat Railway Station or 175 km (4 hours) from Agartala Airport."
  },
  {
    "id": "diu-island",
    "name": "Diu Island & Fort",
    "state": "Dadra & Nagar Haveli and Daman & Diu",
    "region": "west",
    "tagline": "Portuguese Sea Bastions, Nagoa Beach & Hoka Palms",
    "description": "A tranquil island off the southern coast of Gujarat with rich Portuguese heritage. Explore the 1535 AD Diu Sea Fort surrounded by the Arabian Sea, St. Paul's Church, and horseshoe-shaped Nagoa Beach.",
    "elevation": "Sea Level",
    "bestTime": "Oct to May",
    "idealDays": "2 Days",
    "category": "beaches",
    "mood": ["Beaches", "Heritage", "Relaxation"],
    "basePriceINR": 2700,
    "rating": 4.7,
    "reviewsCount": 310,
    "heroImage": "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Diu Fort", "Nagoa Beach", "St Pauls Church", "Naida Caves"],
    "highlights": ["Diu Fort colossal 16th-century sea fortress with cannons and lighthouse", "Naida Caves natural sunlight beam sandstone rock labyrinth", "Horseshoe-shaped Nagoa Beach lined with unique African Hoka palm trees"],
    "nearestHubs": { "airport": "Diu Airport DIU", "railway": "Veraval (90 km) / Delvada (8 km)", "road": "Una-Diu Coastal Highway" },
    "transitSummary": "Direct flights from Mumbai to Diu Airport (DIU) or 90 km drive from Somnath (Veraval)."
  }
]

existing_ids = set()
merged_list = []

for item in destinations_db:
    if item["id"] not in existing_ids:
        existing_ids.add(item["id"])
        merged_list.append(item)

for item in additional_destinations:
    if item["id"] not in existing_ids:
        existing_ids.add(item["id"])
        merged_list.append(item)

final_js = """/**
 * RAAHIYOO 2.0 — Ultimate Master Dataset (120+ Authentic Destinations)
 * Curated for index.html explore grid, search engine, budget calculator, and real maps.
 */

const CURRENCIES = {
  INR: { symbol: '₹', rate: 1, label: 'INR (₹)' },
  USD: { symbol: '$', rate: 0.012, label: 'USD ($)' },
  EUR: { symbol: '€', rate: 0.011, label: 'EUR (€)' },
  AED: { symbol: 'AED ', rate: 0.044, label: 'AED (د.إ)' }
};

const DESTINATIONS = """ + json.dumps(merged_list, indent=2) + """;

if (typeof window !== 'undefined') {
  window.DESTINATIONS = DESTINATIONS;
  window.CURRENCIES = CURRENCIES;
}
"""

with open("/home/linuxlite/.gemini/antigravity/scratch/raahiyoo/js/data.js", "w") as f:
    f.write(final_js)

print(f"ULTIMATE SUCCESS: Written {len(merged_list)} complete destinations to js/data.js!")
