import json

destinations = [
  # --- 1. LADAKH & JAMMU & KASHMIR ---
  {
    "id": "leh-ladakh",
    "name": "Leh Ladakh & Pangong",
    "state": "Ladakh",
    "region": "north",
    "tagline": "The Land of High Passes, Blue Lakes & Monasteries",
    "description": "A breathtaking high-altitude desert surrounded by the Karakoram and Great Himalayas. Famous for the crystal turquoise Pangong Tso lake, magnetic hill, sand dunes of Nubra Valley with double-humped camels, and ancient Buddhist monasteries.",
    "elevation": "3,500 m (11,500 ft)",
    "bestTime": "May to Sep",
    "idealDays": "6 - 8 Days",
    "category": "mountains",
    "mood": ["High Treks", "Adventure", "Photography"],
    "basePriceINR": 4500,
    "rating": 4.9,
    "reviewsCount": 560,
    "heroImage": "https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Pangong Lake", "Nubra Valley", "Khardung La", "Monasteries"],
    "highlights": [
      "Pangong Tso color-changing blue salt lake at 4,225 m",
      "Drive over Khardung La Pass (5,359 m) — one of the world's highest motorable roads",
      "Bactrian double-humped camel safari in white sand dunes of Hunder",
      "Clifftop Thiksey and Hemis ancient Buddhist monasteries"
    ],
    "nearestHubs": { "airport": "Kushok Bakula Rimpochee Airport Leh (IXL)", "railway": "Jammu Tawi (700 km)", "road": "Manali-Leh / Srinagar-Leh Highway" },
    "transitSummary": "Direct flights from Delhi, Mumbai, and Srinagar to Leh Airport (IXL). By road via Manali-Leh highway (open May to Oct) or Srinagar-Kargil-Leh highway."
  },
  {
    "id": "srinagar",
    "name": "Srinagar & Dal Lake",
    "state": "Jammu & Kashmir",
    "region": "north",
    "tagline": "Paradise on Earth, Floating Shikaras & Mughal Gardens",
    "description": "The summer jewel of Kashmir. Glide on Dal Lake in wooden Shikaras, stay in hand-carved cedar houseboats, and stroll through Nishat and Shalimar Mughal Gardens under Chinar trees.",
    "elevation": "1,585 m (5,200 ft)",
    "bestTime": "Mar to Oct & Winter Snow",
    "idealDays": "4 - 5 Days",
    "category": "mountains",
    "mood": ["Romantic", "Heritage", "Snow"],
    "basePriceINR": 3800,
    "rating": 4.8,
    "reviewsCount": 420,
    "heroImage": "https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Dal Lake", "Shikara Ride", "Mughal Gardens", "Houseboats"],
    "highlights": [
      "Early morning floating vegetable market on Dal Lake",
      "Luxury heritage cedar houseboat stay with Kashmiri Kahwa",
      "Terraced cascading fountains of Shalimar and Nishat Gardens",
      "Pari Mahal panoramic view over Dal Lake at sunset"
    ],
    "nearestHubs": { "airport": "Sheikh ul-Alam International Airport Srinagar (SXR)", "railway": "Srinagar (SXR) / Jammu Tawi", "road": "NH-44 via Banihal Qazigund Tunnel" },
    "transitSummary": "Frequent direct flights to Srinagar (SXR) from Delhi, Mumbai, Bengaluru, and Chandigarh. Connected by road via 4-lane NH-44 through Banihal Tunnel."
  },
  {
    "id": "gulmarg",
    "name": "Gulmarg",
    "state": "Jammu & Kashmir",
    "region": "north",
    "tagline": "World's Highest Ski Resort & Snow Gondola",
    "description": "Asia's premier winter sports wonderland. Ride the two-phase Gulmarg Gondola up to Mount Apharwat (13,780 ft) for world-class powder skiing and snowboarding.",
    "elevation": "2,650 m (8,690 ft)",
    "bestTime": "Dec to Mar (Snow) / Apr to Jun (Meadows)",
    "idealDays": "2 - 3 Days",
    "category": "mountains",
    "mood": ["Snow", "Adventure", "High Treks"],
    "basePriceINR": 4200,
    "rating": 4.9,
    "reviewsCount": 350,
    "heroImage": "https://images.unsplash.com/photo-1566837945700-30057527ade0?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Gulmarg Gondola", "Apharwat Peak", "Skiing", "Snowboard"],
    "highlights": [
      "Gulmarg Gondola Phase 2 ascent to Apharwat peak (4,200 m)",
      "Deep powder skiing with certified heli-skiing instructors",
      "St. Mary Historic Church amidst snow pine forests",
      "Frozen Alpather high-altitude lake trek"
    ],
    "nearestHubs": { "airport": "Srinagar Airport SXR (56 km)", "railway": "Jammu Tawi (315 km)", "road": "Srinagar-Tangmarg-Gulmarg Road" },
    "transitSummary": "Fly to Srinagar Airport (SXR), then 1.5-hour taxi drive via Tangmarg. Snow tire chains required on Tangmarg-Gulmarg stretch during winter."
  },
  {
    "id": "pahalgam",
    "name": "Pahalgam & Betaab Valley",
    "state": "Jammu & Kashmir",
    "region": "north",
    "tagline": "The Valley of Shepherds, Pine Groves & Lidder River",
    "description": "A pristine alpine paradise where the Lidder river rushes past pine forests. Base camp for the sacred Amarnath Yatra and gateway to scenic Betaab Valley, Aru Valley, and Baisaran meadow.",
    "elevation": "2,130 m (7,200 ft)",
    "bestTime": "Apr to Oct",
    "idealDays": "3 - 4 Days",
    "category": "mountains",
    "mood": ["Nature", "Romantic", "High Treks"],
    "basePriceINR": 3400,
    "rating": 4.8,
    "reviewsCount": 310,
    "heroImage": "https://images.unsplash.com/photo-1598091383021-15ddea10925d?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Betaab Valley", "Lidder River", "Aru Valley", "Baisaran Meadow"],
    "highlights": [
      "Lidder River grade 3 white water rafting and trout angling",
      "Horseback riding through dense pine forests to Baisaran meadow",
      "Betaab Valley crystal streams and Bollywood film spots",
      "Trek gateway to Kolahoi Glacier and Tarsar Marsar alpine lakes"
    ],
    "nearestHubs": { "airport": "Srinagar Airport (90 km)", "railway": "Jammu Tawi / Udhampur", "road": "NH-44 via Anantnag" },
    "transitSummary": "90 km scenic drive from Srinagar Airport (2.5 hours) along saffron fields of Pampore and Apple orchards of Anantnag."
  },
  {
    "id": "sonamarg",
    "name": "Sonamarg",
    "state": "Jammu & Kashmir",
    "region": "north",
    "tagline": "Meadow of Gold & Thajiwas Glacier",
    "description": "Flanked by towering snow peaks and the roaring Sindh River, Sonamarg is the golden threshold of Ladakh, celebrated for pony treks to Thajiwas Glacier and base for the Great Lakes Trek.",
    "elevation": "2,800 m (9,200 ft)",
    "bestTime": "Apr to Oct",
    "idealDays": "2 - 3 Days",
    "category": "mountains",
    "mood": ["Glaciers", "High Treks", "Adventure"],
    "basePriceINR": 3200,
    "rating": 4.8,
    "reviewsCount": 240,
    "heroImage": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Thajiwas Glacier", "Sindh River", "Kashmir Great Lakes", "Zoji La"],
    "highlights": [
      "Thajiwas Glacier snow sledging throughout summer months",
      "Starting trailhead of world-famous Kashmir Great Lakes Trek",
      "Gateway to high-altitude Zoji La Pass connecting Kashmir to Ladakh"
    ],
    "nearestHubs": { "airport": "Srinagar Airport (80 km)", "railway": "Jammu Tawi", "road": "Srinagar-Leh Highway (NH-1)" },
    "transitSummary": "80 km smooth drive from Srinagar Airport (2 hours) along the Sindh River valley on NH-1."
  },

  # --- 2. HIMACHAL PRADESH ---
  {
    "id": "spiti-valley",
    "name": "Spiti Valley",
    "state": "Himachal Pradesh",
    "region": "north",
    "tagline": "The Middle Land of Ancient Gompas & Lunar Terrains",
    "description": "An untouched trans-Himalayan wonderland. Discover Key Monastery perched on a pyramid cliff, world's highest post office at Hikkim, fossil villages at Langza, and glowing Chandratal Lake.",
    "elevation": "3,800 m (12,500 ft)",
    "bestTime": "Jun to Oct",
    "idealDays": "7 - 9 Days",
    "category": "mountains",
    "mood": ["High Treks", "Adventure", "Offbeat"],
    "basePriceINR": 3500,
    "rating": 4.9,
    "reviewsCount": 290,
    "heroImage": "https://images.unsplash.com/photo-1609137144822-0a25fae06003?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Key Monastery", "Chandratal Lake", "Hikkim Post Office", "Stargazing"],
    "highlights": [
      "1,000-year-old Key Monastery with ancient Buddhist murals",
      "Send physical postcards from Hikkim post office (14,567 ft)",
      "Turquoise crescent Chandratal lake camping",
      "Milky Way dark-sky stargazing in Kibber"
    ],
    "nearestHubs": { "airport": "Bhuntar-Kullu (240 km)", "railway": "Chandigarh / Shimla", "road": "Shimla-Kaza or Manali-Atal Tunnel-Kaza" },
    "transitSummary": "Accessible via Shimla-Kinnaur route year-round or Manali-Atal Tunnel-Kunzum Pass (June to October)."
  },
  {
    "id": "manali",
    "name": "Manali",
    "state": "Himachal Pradesh",
    "region": "north",
    "tagline": "Snow Peaks, Pine Forests & Atal Tunnel Gateway",
    "description": "India's favorite mountain retreat nestled in Kullu valley. Enjoy acoustic music cafes in Old Manali, skiing in Solang, and drive through Atal Tunnel into snowy Lahaul.",
    "elevation": "2,050 m (6,725 ft)",
    "bestTime": "Oct to Jun",
    "idealDays": "4 - 5 Days",
    "category": "mountains",
    "mood": ["Snow", "Adventure", "High Treks"],
    "basePriceINR": 3200,
    "rating": 4.8,
    "reviewsCount": 428,
    "heroImage": "https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Snow Valleys", "Atal Tunnel", "Solang Valley", "Old Manali"],
    "highlights": [
      "Drive through 9.02 km Atal Tunnel into snow-covered Sissu valley",
      "Solang Valley paragliding, ATV rides and snow tubing",
      "Vashisht natural geothermal hot water sulphur springs",
      "Old Manali vibrant riverside live music cafes"
    ],
    "nearestHubs": { "airport": "Kullu-Bhuntar Airport KUU (50 km)", "railway": "Chandigarh (310 km)", "road": "Kiratpur-Manali 4-Lane Expressway" },
    "transitSummary": "Direct luxury AC Volvo buses from Delhi/Chandigarh via new 4-lane Kiratpur expressway (cuts drive time to ~8 hrs). Flights to Bhuntar (KUU)."
  },
  {
    "id": "shimla",
    "name": "Shimla & Kufri",
    "state": "Himachal Pradesh",
    "region": "north",
    "tagline": "Queen of the Hills, UNESCO Toy Train & Mall Road",
    "description": "The historic British summer capital with colonial architecture, the bustling pedestrian Mall Road, Jakhu Temple with giant Hanuman statue, and winter snow adventure in Kufri.",
    "elevation": "2,276 m (7,467 ft)",
    "bestTime": "Year-round / Dec-Feb for Snow",
    "idealDays": "3 - 4 Days",
    "category": "mountains",
    "mood": ["Heritage", "Snow", "Family"],
    "basePriceINR": 2900,
    "rating": 4.7,
    "reviewsCount": 380,
    "heroImage": "https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Mall Road", "UNESCO Toy Train", "Kufri Snow", "Jakhu Temple"],
    "highlights": [
      "Scenic Kalka-Shimla UNESCO Heritage Toy Train ride through 103 tunnels",
      "Stroll along Ridge and Mall Road with Neo-Gothic Christ Church",
      "Jakhu Hill ropeway to the 108 ft Hanuman statue",
      "Kufri winter skiing and horse riding"
    ],
    "nearestHubs": { "airport": "Shimla Jubbarhatti Airport SLV (22 km) / Chandigarh (115 km)", "railway": "Kalka / Shimla", "road": "Himalayan Expressway (NH-5)" },
    "transitSummary": "115 km (3 hours) from Chandigarh International Airport via 4-lane Himalayan Expressway. Connected by Kalka-Shimla toy train."
  },
  {
    "id": "dharamshala",
    "name": "Dharamshala & McLeodganj",
    "state": "Himachal Pradesh",
    "region": "north",
    "tagline": "Little Lhasa, Dalai Lama Residence & Triund Trek",
    "description": "Set against the dramatic snow peaks of the Dhauladhar range. Home to His Holiness Dalai Lama, vibrant Tibetan monasteries, cedar forest trails, and the breathtaking Triund ridge trek.",
    "elevation": "1,457 m (4,780 ft)",
    "bestTime": "Mar to Jun & Sep to Nov",
    "idealDays": "3 - 4 Days",
    "category": "mountains",
    "mood": ["Spiritual", "High Treks", "Peace"],
    "basePriceINR": 2800,
    "rating": 4.8,
    "reviewsCount": 310,
    "heroImage": "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Dalai Lama Temple", "Triund Trek", "Bhagsu Falls", "Dhauladhar"],
    "highlights": [
      "Tsuglagkhang Complex & Namgyal Monastery spiritual mediation",
      "Famous 9 km Triund Ridge Trek under Dhauladhar mountain face",
      "Bhagsunag ancient Shiva temple & cascading waterfalls",
      "St. John in the Wilderness neo-gothic stone church in deodar woods"
    ],
    "nearestHubs": { "airport": "Gaggal-Dharamshala Airport DHM (14 km)", "railway": "Pathankot Cantt (85 km)", "road": "NH-503 via Kangra" },
    "transitSummary": "Direct daily flights to Gaggal Airport (DHM) from Delhi. Overnight luxury Volvo buses from Delhi (470 km) and Chandigarh (240 km)."
  },
  {
    "id": "kasol",
    "name": "Kasol & Parvati Valley",
    "state": "Himachal Pradesh",
    "region": "north",
    "tagline": "Mini Israel of India, Pinewood Trails & Kheerganga",
    "description": "A tranquil riverside village in Parvati Valley famous for Israeli cafes, roaring river trails, Tosh village, and the legendary trek to natural hot sulfur springs at Kheerganga.",
    "elevation": "1,580 m (5,180 ft)",
    "bestTime": "Mar to Jun & Sep to Nov",
    "idealDays": "3 - 5 Days",
    "category": "mountains",
    "mood": ["Adventure", "High Treks", "Offbeat"],
    "basePriceINR": 2400,
    "rating": 4.8,
    "reviewsCount": 390,
    "heroImage": "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Parvati River", "Kheerganga Trek", "Tosh Village", "Israeli Cafes"],
    "highlights": [
      "12 km trek to Kheerganga natural high-altitude hot water springs",
      "Charming wooden houses of Tosh, Chalal and Grahan villages",
      "Relaxing alongside the turquoise roaring Parvati River",
      "Manikaran Sahib sacred Gurudwara hot springs"
    ],
    "nearestHubs": { "airport": "Bhuntar-Kullu Airport (31 km)", "railway": "Chandigarh (270 km)", "road": "Chandigarh-Mandi-Bhuntar-Kasol" },
    "transitSummary": "31 km from Bhuntar Airport / Kullu on Parvati Valley road. Daily Volvo buses from Delhi/Chandigarh drop at Bhuntar."
  },
  {
    "id": "jibhi",
    "name": "Jibhi & Tirthan Valley",
    "state": "Himachal Pradesh",
    "region": "north",
    "tagline": "Hidden Cedar Hamlet, Trout Streams & Jalori Pass",
    "description": "An offbeat fairytale hamlet with Victorian-style wooden cottages, freshwater trout streams, pine forests, Serolsar Lake, and the thrilling 10,800 ft Jalori Pass.",
    "elevation": "1,600 m (5,250 ft)",
    "bestTime": "Year-round",
    "idealDays": "3 - 4 Days",
    "category": "mountains",
    "mood": ["Offbeat", "Peace", "High Treks"],
    "basePriceINR": 2500,
    "rating": 4.9,
    "reviewsCount": 210,
    "heroImage": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Jalori Pass", "Serolsar Lake", "Tirthan River", "Chehni Kothi"],
    "highlights": [
      "Jalori Pass (10,800 ft) trek to sacred Serolsar Lake",
      "Chehni Kothi 1,500-year-old multi-story wooden earthquake-proof tower",
      "Crystal clear Tirthan river angling and Great Himalayan National Park entry"
    ],
    "nearestHubs": { "airport": "Bhuntar-Kullu (50 km)", "railway": "Chandigarh (250 km)", "road": "Aut Tunnel-Jibhi Road" },
    "transitSummary": "Take Volvo bus towards Manali, get down at Aut Tunnel, and take a local cab or bus 30 km up to Jibhi."
  },
  {
    "id": "bir-billing",
    "name": "Bir Billing",
    "state": "Himachal Pradesh",
    "region": "north",
    "tagline": "Paragliding Capital of India & Tibetan Monasteries",
    "description": "World-ranked #2 paragliding takeoff point at Billing (2,400 m) with smooth thermals, landing down in the peaceful Tibetan colony of Bir with monasteries and deer parks.",
    "elevation": "2,400 m (7,870 ft)",
    "bestTime": "Sep to Nov & Mar to May",
    "idealDays": "2 - 3 Days",
    "category": "mountains",
    "mood": ["Adventure", "Peace", "High Treks"],
    "basePriceINR": 3000,
    "rating": 4.9,
    "reviewsCount": 280,
    "heroImage": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Tandem Paragliding", "Chokling Monastery", "Sunset Point", "Tea Gardens"],
    "highlights": [
      "Tandem 20-30 minute paragliding flight over the Dhauladhar valley",
      "Chokling & Palpung Sherabling ancient Tibetan monasteries",
      "Tea factory tours and Tibetan handicrafts market"
    ],
    "nearestHubs": { "airport": "Dharamshala Airport (68 km)", "railway": "Pathankot (140 km) / Ahju Toy Train", "road": "NH-154 via Baijnath" },
    "transitSummary": "68 km from Gaggal-Dharamshala Airport. Direct buses from Delhi/Chandigarh via Baijnath."
  },
  {
    "id": "dalhousie",
    "name": "Dalhousie & Khajjiar",
    "state": "Himachal Pradesh",
    "region": "north",
    "tagline": "Mini Switzerland of India & Colonial Pine Hills",
    "description": "A charming hill station spread across five forested hills, paired with the emerald meadow and lake of Khajjiar encircled by towering cedar deodars.",
    "elevation": "1,970 m (6,460 ft)",
    "bestTime": "Mar to Jun & Dec to Feb (Snow)",
    "idealDays": "3 - 4 Days",
    "category": "mountains",
    "mood": ["Romantic", "Heritage", "Snow"],
    "basePriceINR": 2800,
    "rating": 4.7,
    "reviewsCount": 260,
    "heroImage": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Khajjiar Meadow", "Panchpula", "Dainkund Peak", "Bakrota Hills"],
    "highlights": [
      "Khajjiar meadow with floating island lake and zorbing",
      "Dainkund Peak (Singing Hill) 360-degree snow panorama",
      "Panchpula cascading waterfalls and historic monument"
    ],
    "nearestHubs": { "airport": "Pathankot (75 km) / Gaggal (105 km)", "railway": "Pathankot Cantt (PTKC)", "road": "Pathankot-Dalhousie Road" },
    "transitSummary": "75 km (2.5 hours) from Pathankot Railway Station via scenic mountain road."
  },

  # --- 3. UTTARAKHAND ---
  {
    "id": "kedarnath",
    "name": "Kedarnath Dham",
    "state": "Uttarakhand",
    "region": "north",
    "tagline": "The Holy 11th Jyotirlinga in Garhwal Himalayas",
    "description": "One of India's holiest Chota Char Dham pilgrimage shrines, dedicated to Lord Shiva and backed by snow-clad 6,940 m Mount Kedarnath peak near Mandakini river.",
    "elevation": "3,583 m (11,755 ft)",
    "bestTime": "May to Jun & Sep to Oct",
    "idealDays": "4 - 5 Days",
    "category": "sacred",
    "mood": ["Spiritual", "High Treks", "Glaciers"],
    "basePriceINR": 3800,
    "rating": 4.9,
    "reviewsCount": 610,
    "heroImage": "https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=1200&q=80",
    "tags": ["11th Jyotirlinga", "Char Dham", "Mandakini River", "Gaurikund Trek"],
    "highlights": [
      "16 km mountain trek from Gaurikund alongside rushing Mandakini River",
      "8th-century stone temple that miraculously survived 2013 flash floods",
      "Evening Maha Aarti under the towering Kedarnath snow face",
      "Bhairavnath Temple clifftop viewpoint overlooking the valley"
    ],
    "nearestHubs": { "airport": "Jolly Grant Dehradun DED (230 km)", "railway": "Rishikesh / Haridwar", "road": "NH-107 via Rudraprayag to Gaurikund" },
    "transitSummary": "Drive from Rishikesh/Haridwar to Sonprayag/Gaurikund (220 km), followed by a 16 km trek or heli-shuttle from Guptkashi/Phata/Sersi."
  },
  {
    "id": "badrinath",
    "name": "Badrinath & Mana",
    "state": "Uttarakhand",
    "region": "north",
    "tagline": "Sacred Vaikuntha of Lord Vishnu & First Indian Village",
    "description": "Perched between Nar and Narayana mountain ranges along the Alaknanda River. Visit the vibrant Badrinath Temple, Tapt Kund hot springs, and Mana — India's first village near the Tibet border.",
    "elevation": "3,300 m (10,800 ft)",
    "bestTime": "May to Jun & Sep to Oct",
    "idealDays": "4 - 5 Days",
    "category": "sacred",
    "mood": ["Spiritual", "Heritage", "High Treks"],
    "basePriceINR": 3600,
    "rating": 4.9,
    "reviewsCount": 450,
    "heroImage": "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Badrinath Temple", "Mana Village", "Alaknanda River", "Vyas Gufa"],
    "highlights": [
      "Ancient Badrinath Temple with colorful facade",
      "Mana Village: Vyas Gufa, Ganesh Gufa & Bhim Pul stone bridge over Saraswati River",
      "Tapt Kund natural sulfur bath before temple entry",
      "Vasudhara Falls 400 ft cascading mountain waterfall trek"
    ],
    "nearestHubs": { "airport": "Dehradun Airport (310 km)", "railway": "Rishikesh / Yog Nagari", "road": "NH-07 All-Weather Chardham Highway" },
    "transitSummary": "Accessible by road via NH-07 from Rishikesh/Haridwar through Devprayag, Rudraprayag, and Joshimath directly up to the temple entrance."
  },
  {
    "id": "rishikesh",
    "name": "Rishikesh",
    "state": "Uttarakhand",
    "region": "north",
    "tagline": "Yoga Capital of the World & Ganga River Rafting",
    "description": "Where the sacred Ganges emerges from the Himalayas. Famous for Ram Jhula, world-class white water rafting, Beatles Ashram, and the spellbinding Triveni Ghat evening Ganga Aarti.",
    "elevation": "372 m (1,220 ft)",
    "bestTime": "Sep to May",
    "idealDays": "2 - 3 Days",
    "category": "sacred",
    "mood": ["Adventure", "Spiritual", "Wellness"],
    "basePriceINR": 2400,
    "rating": 4.8,
    "reviewsCount": 580,
    "heroImage": "https://images.unsplash.com/photo-1598091383021-15ddea10925d?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Ganga Rafting", "Triveni Aarti", "Beatles Ashram", "Bungee Jumping"],
    "highlights": [
      "16-24 km grade 3-4 white water rafting through Marine Drive and Shivpuri",
      "Triveni Ghat and Parmarth Niketan grand sunset Ganga Maha Aarti",
      "Beatles Ashram (Chaurasi Kutia) graffiti meditation domes in Rajaji National Park",
      "India's highest bungee jump (83 meters) in Mohan Chatti"
    ],
    "nearestHubs": { "airport": "Dehradun Jolly Grant DED (18 km)", "railway": "Yog Nagari Rishikesh (YNRK) / Haridwar", "road": "NH-58 / Delhi-Dehradun Expressway" },
    "transitSummary": "18 km from Dehradun Airport (DED). Direct trains to Yog Nagari Rishikesh (YNRK) or 4.5-hour drive from Delhi via NH-58 expressway."
  },
  {
    "id": "auli",
    "name": "Auli Ski Slopes",
    "state": "Uttarakhand",
    "region": "north",
    "tagline": "Premier Himalayan Ski Slopes & Nanda Devi Panoramas",
    "description": "India's signature skiing paradise. Glide on powdered snow slopes with direct 180-degree views of India's 2nd highest peak Nanda Devi (7,816 m), connected by Asia's longest cable car.",
    "elevation": "2,800 m (9,200 ft)",
    "bestTime": "Dec to Mar (Skiing) / Apr to Jun (Lush)",
    "idealDays": "3 - 4 Days",
    "category": "mountains",
    "mood": ["Snow", "Adventure", "High Treks"],
    "basePriceINR": 3800,
    "rating": 4.8,
    "reviewsCount": 290,
    "heroImage": "https://images.unsplash.com/photo-1566837945700-30057527ade0?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Auli Cable Car", "Nanda Devi View", "Ski Slopes", "Gorson Bugyal"],
    "highlights": [
      "Joshimath to Auli 4 km aerial ropeway cable car",
      "Skiing courses certified by GMVN with snow guns and chair lifts",
      "Gorson Bugyal high-altitude alpine meadow trek (3,050 m)",
      "Mirror reflection of peaks on Auli Artificial Lake"
    ],
    "nearestHubs": { "airport": "Dehradun Airport (270 km)", "railway": "Rishikesh / Haridwar", "road": "NH-07 to Joshimath" },
    "transitSummary": "Drive from Rishikesh/Haridwar to Joshimath (250 km), then take the 20-minute cable car or a 14 km winding road up to Auli."
  },
  {
    "id": "nainital",
    "name": "Nainital & Bhimtal",
    "state": "Uttarakhand",
    "region": "north",
    "tagline": "The City of Lakes, Naina Devi & Kumaon Hills",
    "description": "A picturesque lake resort set around eye-shaped Naini Lake, with panoramic views of snow peaks from Snow View Point, Naina Devi Temple, and nearby Bhimtal.",
    "elevation": "2,084 m (6,837 ft)",
    "bestTime": "Mar to Jun & Dec to Jan (Snow)",
    "idealDays": "3 - 4 Days",
    "category": "mountains",
    "mood": ["Family", "Romantic", "Nature"],
    "basePriceINR": 2800,
    "rating": 4.7,
    "reviewsCount": 410,
    "heroImage": "https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Naini Lake", "Boating", "Mall Road", "Naina Peak"],
    "highlights": [
      "Yachting and boating on emerald Naini Lake",
      "Naina Peak (8,579 ft) highest viewpoint in Nainital",
      "Scenic cable car ropeway to Snow View Point",
      "Bhimtal island aquarium and peaceful waters"
    ],
    "nearestHubs": { "airport": "Pantnagar PGH (65 km) / Delhi (300 km)", "railway": "Kathgodam KGM (34 km)", "road": "NH-109 via Haldwani" },
    "transitSummary": "34 km (1 hour) from Kathgodam Railway Station. Shatabdi / Ranikhet Express connects Delhi to Kathgodam."
  },
  {
    "id": "mussoorie",
    "name": "Mussoorie & Dhanaulti",
    "state": "Uttarakhand",
    "region": "north",
    "tagline": "Queen of the Hills, Kempty Falls & George Everest",
    "description": "Perched on a horseshoe ridge overlooking the Doon Valley, Mussoorie offers colonial heritage, Kempty Falls, the scenic Camel Back Road, and George Everest Peak.",
    "elevation": "2,005 m (6,578 ft)",
    "bestTime": "Mar to Jun & Sep to Nov",
    "idealDays": "3 - 4 Days",
    "category": "mountains",
    "mood": ["Romantic", "Heritage", "Family"],
    "basePriceINR": 2900,
    "rating": 4.7,
    "reviewsCount": 370,
    "heroImage": "https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Mall Road", "Kempty Falls", "George Everest", "Gun Hill"],
    "highlights": [
      "George Everest House and sunset ridge overlooking snow peaks",
      "Gun Hill ropeway with 360-degree views of Himalayan range",
      "Cascading Kempty Falls and Company Garden",
      "Dhanaulti eco-parks and tranquil deodar groves"
    ],
    "nearestHubs": { "airport": "Dehradun Jolly Grant DED (55 km)", "railway": "Dehradun DDN (34 km)", "road": "Dehradun-Mussoorie Highway" },
    "transitSummary": "34 km uphill drive from Dehradun Railway Station (1.2 hours) or 55 km from Dehradun Airport."
  },
  {
    "id": "chopta",
    "name": "Chopta & Tungnath",
    "state": "Uttarakhand",
    "region": "north",
    "tagline": "Mini Switzerland & World's Highest Shiva Temple",
    "description": "An unspoiled alpine meadow in Kedarnath Wildlife Sanctuary. Base for the 3.5 km trek to Tungnath (3,680 m) — the highest of all Panch Kedar temples — and the Chandrashila summit.",
    "elevation": "2,680 m (8,790 ft)",
    "bestTime": "Apr to Jun & Sep to Nov / Winter Snow",
    "idealDays": "3 - 4 Days",
    "category": "mountains",
    "mood": ["High Treks", "Spiritual", "Offbeat"],
    "basePriceINR": 2600,
    "rating": 4.9,
    "reviewsCount": 320,
    "heroImage": "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Tungnath Temple", "Chandrashila Summit", "Deoriatal Lake", "Meadows"],
    "highlights": [
      "Trek to 1,000-year-old Tungnath Temple at 12,073 ft",
      "Chandrashila Summit (13,000 ft) with 360-degree panorama of Nanda Devi, Trishul, and Chaukhamba peaks",
      "Deoriatal emerald lake with reflection of Chaukhamba massif"
    ],
    "nearestHubs": { "airport": "Dehradun DED (220 km)", "railway": "Rishikesh (200 km)", "road": "Rudraprayag-Ukhimath-Chopta Road" },
    "transitSummary": "Drive from Rishikesh/Haridwar to Chopta via Rudraprayag and Ukhimath (200 km, ~6.5 hours)."
  },

  # --- 4. RAJASTHAN ---
  {
    "id": "jaipur",
    "name": "Jaipur Pink City",
    "state": "Rajasthan",
    "region": "west",
    "tagline": "The Royal Pink City of Fortresses & Palaces",
    "description": "UNESCO World Heritage capital of Rajasthan. Marvel at the intricate honeycomb windows of Hawa Mahal, the mirror palace of Amer Fort, and grand City Palace.",
    "elevation": "431 m (1,414 ft)",
    "bestTime": "Oct to Mar",
    "idealDays": "3 - 4 Days",
    "category": "heritage",
    "mood": ["Heritage", "Shopping", "Food"],
    "basePriceINR": 2800,
    "rating": 4.8,
    "reviewsCount": 590,
    "heroImage": "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Hawa Mahal", "Amer Fort", "City Palace", "Nahargarh"],
    "highlights": [
      "Amer Fort grand ramparts, Sheesh Mahal and elephant ride",
      "Hawa Mahal (Palace of Winds) with 953 jharokhas",
      "Nahargarh Fort panoramic sunset view over the Pink City",
      "World's largest stone sundial at Jantar Mantar observatory"
    ],
    "nearestHubs": { "airport": "Jaipur International Airport JAI", "railway": "Jaipur Junction JP", "road": "Delhi-Jaipur Expressway (NE-4)" },
    "transitSummary": "Direct flights to Jaipur (JAI) from all major Indian metros. 3.5-hour drive from Delhi via Delhi-Mumbai Expressway or Vande Bharat Express."
  },
  {
    "id": "udaipur",
    "name": "Udaipur City of Lakes",
    "state": "Rajasthan",
    "region": "west",
    "tagline": "Venice of the East, Lake Pichola & Palaces",
    "description": "Surrounded by the Aravali hills and shimmering azure lakes. Famous for the floating Lake Palace, majestic City Palace complex, and sunset boat cruises on Lake Pichola.",
    "elevation": "598 m (1,962 ft)",
    "bestTime": "Oct to Mar",
    "idealDays": "3 - 4 Days",
    "category": "heritage",
    "mood": ["Romantic", "Heritage", "Luxury"],
    "basePriceINR": 3400,
    "rating": 4.9,
    "reviewsCount": 510,
    "heroImage": "https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Lake Pichola", "City Palace", "Taj Lake Palace", "Fateh Sagar"],
    "highlights": [
      "Sunset boat cruise on Lake Pichola past Jag Mandir Island Palace",
      "Grand City Palace Museum with peacock courtyards and crystal gallery",
      "Saheliyon-ki-Bari royal garden fountains",
      "Monsoon Palace (Sajjangarh) hilltop panoramic view"
    ],
    "nearestHubs": { "airport": "Maharana Pratap Airport Udaipur UDR", "railway": "Udaipur City UDZ", "road": "NH-48 via Ahmedabad / Jaipur" },
    "transitSummary": "Direct flights from Mumbai, Delhi, Bengaluru, and Jaipur to Udaipur (UDR). Direct Vande Bharat from Jaipur."
  },
  {
    "id": "jaisalmer",
    "name": "Jaisalmer Desert Dunes",
    "state": "Rajasthan",
    "region": "west",
    "tagline": "The Golden Fort & Thar Desert Sand Dunes",
    "description": "Rising from the heart of the Great Thar Desert. Live inside the world's only living golden sandstone fort, ride camels over Sam Sand Dunes, and camp under starry desert skies.",
    "elevation": "225 m (738 ft)",
    "bestTime": "Oct to Mar",
    "idealDays": "3 - 4 Days",
    "category": "heritage",
    "mood": ["Adventure", "Heritage", "Desert"],
    "basePriceINR": 3200,
    "rating": 4.8,
    "reviewsCount": 380,
    "heroImage": "https://images.unsplash.com/photo-1577717903315-1691ae25ab3f?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Golden Fort", "Sam Sand Dunes", "Camel Safari", "Patwon Ki Haveli"],
    "highlights": [
      "Explore 12th-century Sonar Qila (Golden Fort) where 4,000 residents live",
      "Sunset camel safari and dune bashing at Sam Sand Dunes",
      "Rajasthani folk music, Kalbeliya dance and glamping under desert stars",
      "Intricately carved yellow sandstone Patwon ki Haveli"
    ],
    "nearestHubs": { "airport": "Jaisalmer Airport JSA (seasonal) / Jodhpur (280 km)", "railway": "Jaisalmer JSA", "road": "NH-11 / NH-68" },
    "transitSummary": "Direct seasonal flights to Jaisalmer (JSA) or 4.5-hour smooth drive from Jodhpur Airport (JDH). Direct overnight trains from Delhi/Jaipur."
  },
  {
    "id": "jodhpur",
    "name": "Jodhpur Blue City",
    "state": "Rajasthan",
    "region": "west",
    "tagline": "The Sun City, Mehrangarh Fort & Indigo Alleys",
    "description": "Guarded by the colossal clifftop Mehrangarh Fort. Wander through medieval blue-painted streets in the old city, explore Umaid Bhawan Palace, and savor rich pyaaz kachoris.",
    "elevation": "231 m (758 ft)",
    "bestTime": "Oct to Mar",
    "idealDays": "2 - 3 Days",
    "category": "heritage",
    "mood": ["Heritage", "Photography", "Food"],
    "basePriceINR": 2800,
    "rating": 4.8,
    "reviewsCount": 340,
    "heroImage": "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Mehrangarh Fort", "Blue City", "Umaid Bhawan", "Jaswant Thada"],
    "highlights": [
      "Mehrangarh Fort ramparts with royal palanquins and howdahs",
      "Zipline (Flying Fox) across fort moats and desert lakes",
      "Walk the indigo-blue lanes around Clock Tower & Sardar Market",
      "Jaswant Thada white marble royal cenotaph"
    ],
    "nearestHubs": { "airport": "Jodhpur Airport JDH", "railway": "Jodhpur Junction JU", "road": "NH-62 / Amritsar-Jamnagar Expressway" },
    "transitSummary": "Direct flights from Delhi, Mumbai, Bengaluru, and Ahmedabad to Jodhpur (JDH). Direct Vande Bharat trains."
  },

  # --- 5. GOA & MAHARASHTRA ---
  {
    "id": "goa",
    "name": "Goa Beaches",
    "state": "Goa",
    "region": "west",
    "tagline": "Sun, Sand, Portuguese Heritage & Vibrant Coastlines",
    "description": "India's beach capital! Experience water sports, beach shacks, night markets in North Goa, and tranquil white sand beaches, spice plantations, and churches in South Goa.",
    "elevation": "Sea Level",
    "bestTime": "Oct to May",
    "idealDays": "4 - 6 Days",
    "category": "beaches",
    "mood": ["Beaches", "Nightlife", "Heritage"],
    "basePriceINR": 3500,
    "rating": 4.8,
    "reviewsCount": 680,
    "heroImage": "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Palolem Beach", "Baga Beach", "Old Goa Churches", "Dudhsagar Falls"],
    "highlights": [
      "UNESCO Heritage Basilica of Bom Jesus and Se Cathedral in Old Goa",
      "Crescent white sands and dolphin spotting at Palolem Beach",
      "Water sports (jet-ski, parasailing, scuba) at Calangute and Baga",
      "Fontainhas vibrant Latin Quarter walking heritage tour"
    ],
    "nearestHubs": { "airport": "Manohar Int Airport MOPA (GOX) / Dabolim (GOI)", "railway": "Madgaon (MAO) / Thivim (THVM)", "road": "NH-66 / Mumbai-Goa Highway" },
    "transitSummary": "Fly directly into Mopa (GOX) or Dabolim (GOI). Vande Bharat / Tejas Express trains connect Mumbai to Madgaon in ~7.5 hours."
  },
  {
    "id": "lonavala",
    "name": "Lonavala & Khandala",
    "state": "Maharashtra",
    "region": "west",
    "tagline": "Jewel of Sahyadris, Monsoon Waterfalls & Forts",
    "description": "The quintessential Western Ghats monsoon getaway. Famous for mist-covered Sahyadri ridges, Tiger Point, Bhushi Dam waterfalls, and Karla Buddhist rock caves.",
    "elevation": "624 m (2,047 ft)",
    "bestTime": "Jul to Feb (Monsoon & Winter)",
    "idealDays": "2 - 3 Days",
    "category": "mountains",
    "mood": ["Monsoon", "Nature", "Family"],
    "basePriceINR": 2600,
    "rating": 4.6,
    "reviewsCount": 360,
    "heroImage": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Tiger Point", "Bhushi Dam", "Karla Caves", "Lohagad Fort"],
    "highlights": [
      "Tiger Point & Lion Point clifftop valley views",
      "Lohagad Fort trek with Vinchu Kata scorpion tail ridge",
      "2nd century BC Buddhist Karla & Bhaja rock-cut caves",
      "Tasting iconic hot Lonavala chikki and fudge"
    ],
    "nearestHubs": { "airport": "Pune Airport PNQ (65 km) / Mumbai (85 km)", "railway": "Lonavala LNL", "road": "Mumbai-Pune Expressway" },
    "transitSummary": "Located right on the 6-lane Mumbai-Pune Expressway — 1.5 hours from Pune and 2 hours from Mumbai."
  },
  {
    "id": "mahabaleshwar",
    "name": "Mahabaleshwar & Panchgani",
    "state": "Maharashtra",
    "region": "west",
    "tagline": "Strawberry Capital, Venna Lake & Sahyadri Points",
    "description": "Perched on the high Sahyadri plateau. Famous for lush strawberry farms, Arthur Seat valley view, boat rides on Venna Lake, and Table Land plateau in Panchgani.",
    "elevation": "1,353 m (4,439 ft)",
    "bestTime": "Oct to Jun",
    "idealDays": "3 - 4 Days",
    "category": "mountains",
    "mood": ["Romantic", "Nature", "Family"],
    "basePriceINR": 3000,
    "rating": 4.7,
    "reviewsCount": 310,
    "heroImage": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Strawberry Farms", "Arthur Seat", "Venna Lake", "Pratapgad Fort"],
    "highlights": [
      "Fresh strawberry picking & strawberry cream at Mapro Garden",
      "Arthur Seat & Wilson Point (Sunrise Point) viewpoints",
      "Historic Pratapgad Fort battle site of Chhatrapati Shivaji Maharaj",
      "Boating on tranquil Venna Lake"
    ],
    "nearestHubs": { "airport": "Pune Airport (120 km)", "railway": "Wathar (60 km) / Pune", "road": "NH-48 via Wai / Shirwal" },
    "transitSummary": "120 km (3 hours) from Pune Airport via NH-48 and Pasarni Ghat."
  },

  # --- 6. KERALA, KARNATAKA & TAMIL NADU ---
  {
    "id": "munnar",
    "name": "Munnar Tea Hills",
    "state": "Kerala",
    "region": "south",
    "tagline": "Emerald Tea Plantations, Mist & Nilgiri Tahr",
    "description": "Sprawling rolling hills blanketed in velvety green tea estates at the confluence of three mountain streams. Home to Anamudi — South India's highest peak — and the endangered Nilgiri Tahr.",
    "elevation": "1,600 m (5,250 ft)",
    "bestTime": "Sep to May",
    "idealDays": "3 - 4 Days",
    "category": "mountains",
    "mood": ["Nature", "Romantic", "Tea Hills"],
    "basePriceINR": 3200,
    "rating": 4.9,
    "reviewsCount": 490,
    "heroImage": "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Tea Estates", "Eravikulam", "Anamudi Peak", "Mattupetty Dam"],
    "highlights": [
      "Spot endangered mountain goats (Nilgiri Tahr) in Eravikulam National Park",
      "Tata Tea Museum plucking and processing heritage experience",
      "Speedboating on Mattupetty Lake with mountain echoes",
      "Top Station clifftop clouds view looking into Tamil Nadu valley"
    ],
    "nearestHubs": { "airport": "Cochin International Airport COK (110 km)", "railway": "Aluva (110 km) / Ernakulam (130 km)", "road": "NH-85 Kochi-Dhanushkodi Highway" },
    "transitSummary": "110 km scenic drive from Kochi Airport (COK) through Cheeyappara and Valara waterfalls (3.5 hours)."
  },
  {
    "id": "alleppey",
    "name": "Alleppey Houseboats",
    "state": "Kerala",
    "region": "south",
    "tagline": "Venice of the East & Backwater Houseboat Cruises",
    "description": "A tranquil network of palm-fringed canals, lagoons, and paddy fields. Drift on traditional thatched Kettuvallam houseboats savoring fresh Karimeen fish fry.",
    "elevation": "Sea Level",
    "bestTime": "Sep to Mar",
    "idealDays": "2 - 3 Days",
    "category": "beaches",
    "mood": ["Romantic", "Waterways", "Relaxation"],
    "basePriceINR": 4000,
    "rating": 4.9,
    "reviewsCount": 470,
    "heroImage": "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Houseboat Cruise", "Vembanad Lake", "Backwaters", "Marari Beach"],
    "highlights": [
      "Overnight luxury houseboat cruise on Vembanad Lake",
      "Village canoe Shikara rides through narrow village canals",
      "Sunset at pristine white sand Marari Beach",
      "Authentic Kerala Sadya lunch cooked onboard"
    ],
    "nearestHubs": { "airport": "Cochin Airport COK (75 km)", "railway": "Alappuzha ALLP", "road": "NH-66 Coastal Highway" },
    "transitSummary": "75 km from Kochi Airport (COK). Direct trains to Alappuzha Railway Station (ALLP)."
  },
  {
    "id": "varkala",
    "name": "Varkala Cliff",
    "state": "Kerala",
    "region": "south",
    "tagline": "Red Laterite Ocean Cliffs & Papanasam Beach",
    "description": "The only place in southern Kerala where towering red laterite cliffs overlook the Arabian Sea. Clifftop yoga cafes, surfing waves, and sacred Papanasam mineral springs.",
    "elevation": "Sea Level",
    "bestTime": "Oct to Apr",
    "idealDays": "2 - 3 Days",
    "category": "beaches",
    "mood": ["Beaches", "Wellness", "Relaxation"],
    "basePriceINR": 2800,
    "rating": 4.8,
    "reviewsCount": 310,
    "heroImage": "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Varkala Cliff", "Papanasam Beach", "Surfing", "Sunset Cafes"],
    "highlights": [
      "Clifftop promenade lined with seafood restaurants and yoga schools",
      "Papanasam sacred natural spring beach",
      "Beginner surf lessons at Black Beach",
      "2,000-year-old Janardhana Swamy Vishnu Temple"
    ],
    "nearestHubs": { "airport": "Trivandrum Airport TRV (45 km)", "railway": "Varkala Sivagiri VAK", "road": "NH-66" },
    "transitSummary": "45 km (1 hour) from Trivandrum International Airport (TRV). Direct express trains stop at Varkala Sivagiri station."
  },
  {
    "id": "hampi",
    "name": "Hampi",
    "state": "Karnataka",
    "region": "south",
    "tagline": "UNESCO Bouldered Ruins of Vijayanagara Empire",
    "description": "An open-air museum of giant golden granite boulders, ancient palace ruins, monolithic statues, and the famous stone chariot of the 14th-century Vijayanagara Empire on Tungabhadra river.",
    "elevation": "467 m (1,532 ft)",
    "bestTime": "Oct to Mar",
    "idealDays": "3 - 4 Days",
    "category": "heritage",
    "mood": ["Heritage", "Photography", "Offbeat"],
    "basePriceINR": 2700,
    "rating": 4.9,
    "reviewsCount": 430,
    "heroImage": "https://images.unsplash.com/photo-1600100397608-f010e47f985a?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Stone Chariot", "Virupaksha Temple", "Matanga Hill", "Coracle Ride"],
    "highlights": [
      "Iconic monolithic Stone Chariot & musical pillars at Vijaya Vittala Temple",
      "Sunrise panorama over boulder ocean from Matanga Hill",
      "Active 7th-century Virupaksha Temple with sacred elephant Lakshmi",
      "Traditional round bamboo coracle boat ride on Tungabhadra River"
    ],
    "nearestHubs": { "airport": "Jindal Vijayanagar Airport VDY (35 km) / Hubli (140 km)", "railway": "Hosapete HPT (13 km)", "road": "NH-50 / NH-67" },
    "transitSummary": "13 km from Hosapete Railway Station (HPT). Direct overnight Hampi Express trains from Bengaluru and Goa."
  },
  {
    "id": "coorg",
    "name": "Coorg Coffee Hills",
    "state": "Karnataka",
    "region": "south",
    "tagline": "Scotland of India, Coffee Estates & Abbey Falls",
    "description": "Lush misty green hills blanketed in coffee plantations, spice gardens, cascading Abbey Falls, Raja Seat sunsets, and the Tibetan Golden Temple at Bylakuppe.",
    "elevation": "1,150 m (3,770 ft)",
    "bestTime": "Oct to May",
    "idealDays": "3 - 4 Days",
    "category": "mountains",
    "mood": ["Nature", "Romantic", "Coffee Hills"],
    "basePriceINR": 3200,
    "rating": 4.8,
    "reviewsCount": 460,
    "heroImage": "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Coffee Plantations", "Abbey Falls", "Namdroling Monastery", "Raja Seat"],
    "highlights": [
      "Stay in authentic heritage coffee & cardamom plantation homestays",
      "Namdroling Golden Temple with 40-ft gilded Buddha statues in Bylakuppe",
      "Roaring Abbey Falls surrounded by spice groves",
      "Raja Seat hilltop musical fountain sunset"
    ],
    "nearestHubs": { "airport": "Kannur Airport CNN (85 km) / Mangalore (135 km) / Bengaluru (260 km)", "railway": "Mysuru MYS (115 km)", "road": "Mysuru-Madikeri Highway" },
    "transitSummary": "115 km from Mysuru Railway Station (2.5 hours) or 260 km from Bengaluru via Mysore Expressway."
  },
  {
    "id": "ooty",
    "name": "Ooty & Nilgiris",
    "state": "Tamil Nadu",
    "region": "south",
    "tagline": "Queen of Nilgiris, Heritage Toy Train & Tea Hills",
    "description": "South India's most famous hill station in the Blue Mountains. Ride the UNESCO Nilgiri Mountain Toy Train, climb Doddabetta Peak (2,637 m), and stroll through lush Botanical Gardens.",
    "elevation": "2,240 m (7,350 ft)",
    "bestTime": "Year-round",
    "idealDays": "3 - 4 Days",
    "category": "mountains",
    "mood": ["Romantic", "Family", "Heritage"],
    "basePriceINR": 3000,
    "rating": 4.7,
    "reviewsCount": 480,
    "heroImage": "https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Nilgiri Toy Train", "Doddabetta Peak", "Botanical Garden", "Pykara Lake"],
    "highlights": [
      "UNESCO steam rack-and-pinion Nilgiri Mountain Railway toy train ride",
      "Doddabetta Peak 360-degree telescope view across three states",
      "Speedboating on Pykara Lake and Pykara Waterfalls",
      "Government Botanical Garden with 650+ species of exotic flora"
    ],
    "nearestHubs": { "airport": "Coimbatore Airport CJB (88 km)", "railway": "Mettupalayam MTP (50 km) / Udhagamandalam UAM", "road": "Mettupalayam-Ooty Ghat Road (36 Hairpin Bends)" },
    "transitSummary": "88 km from Coimbatore Airport (CJB). Connected from Mettupalayam via the Nilgiri Mountain toy train or ghat road."
  },
  {
    "id": "rameswaram",
    "name": "Rameswaram & Dhanushkodi",
    "state": "Tamil Nadu",
    "region": "south",
    "tagline": "Char Dham Island, Ramanathaswamy Corridors & Ram Setu",
    "description": "A sacred island connected by the iconic Pamban Sea Bridge. Features the 1,000-pillar corridor of Ramanathaswamy Temple, 22 sacred teertham wells, and the ghost town of Dhanushkodi near Ram Setu.",
    "elevation": "10 m (33 ft)",
    "bestTime": "Oct to Apr",
    "idealDays": "2 - 3 Days",
    "category": "sacred",
    "mood": ["Spiritual", "Heritage", "Ocean"],
    "basePriceINR": 2800,
    "rating": 4.8,
    "reviewsCount": 390,
    "heroImage": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Pamban Bridge", "Ramanathaswamy Temple", "Dhanushkodi", "Ram Setu"],
    "highlights": [
      "Drive across Pamban Sea Bridge over the turquoise Indian Ocean",
      "World's longest temple corridor with 1,212 carved granite pillars",
      "Bathing in 22 holy freshwater Teerthams inside the temple complex",
      "Dhanushkodi ghost town beach where Indian Ocean meets Bay of Bengal"
    ],
    "nearestHubs": { "airport": "Madurai Airport IXM (175 km)", "railway": "Rameswaram RMM", "road": "NH-87 across Pamban Road Bridge" },
    "transitSummary": "175 km (3 hours) from Madurai International Airport (IXM). Direct express trains across Pamban Bridge directly to Rameswaram (RMM)."
  },
  {
    "id": "kanyakumari",
    "name": "Kanyakumari",
    "state": "Tamil Nadu",
    "region": "south",
    "tagline": "Southernmost Tip of Mainland India & 3 Oceans",
    "description": "Where the Arabian Sea, Indian Ocean, and Bay of Bengal converge. Watch simultaneous sunrise and sunset from the same beach, and take a ferry to the Vivekananda Rock Memorial.",
    "elevation": "Sea Level",
    "bestTime": "Oct to Mar",
    "idealDays": "2 Days",
    "category": "beaches",
    "mood": ["Ocean", "Spiritual", "Heritage"],
    "basePriceINR": 2600,
    "rating": 4.7,
    "reviewsCount": 350,
    "heroImage": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Vivekananda Rock", "Thiruvalluvar Statue", "Triveni Sangam", "Sunset"],
    "highlights": [
      "Ferry ride to Vivekananda Rock Memorial and 133-ft Thiruvalluvar Statue",
      "Triveni Sangam three-ocean water confluence bath",
      "Witness simultaneous sunrise and sunset over the ocean horizon",
      "3,000-year-old Bhagavathy Amman Temple"
    ],
    "nearestHubs": { "airport": "Trivandrum Airport TRV (90 km)", "railway": "Kanyakumari CAPE", "road": "NH-44 (Southern Terminus)" },
    "transitSummary": "90 km (2.5 hours) from Trivandrum Airport (TRV). Direct express trains from all major Indian cities."
  },

  # --- 7. UTTAR PRADESH, BIHAR & MADHYA PRADESH ---
  {
    "id": "varanasi",
    "name": "Varanasi (Kashi)",
    "state": "Uttar Pradesh",
    "region": "north",
    "tagline": "World's Oldest Living City & Ganga Maha Aarti",
    "description": "The spiritual heart of India on the banks of sacred River Ganga. Experience the golden Kashi Vishwanath corridor, morning boat rides past historic ghats, and grand evening Dashashwamedh Aarti.",
    "elevation": "81 m (265 ft)",
    "bestTime": "Oct to Mar",
    "idealDays": "2 - 3 Days",
    "category": "sacred",
    "mood": ["Spiritual", "Heritage", "Food"],
    "basePriceINR": 2400,
    "rating": 4.9,
    "reviewsCount": 720,
    "heroImage": "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Kashi Vishwanath", "Ganga Aarti", "Assi Ghat", "Sarnath"],
    "highlights": [
      "Mesmerizing multi-tiered brass lamp Ganga Aarti at Dashashwamedh Ghat",
      "Kashi Vishwanath Golden Temple darshan & corridor walk",
      "Dawn boat ride past 84 historic stone ghats from Assi to Manikarnika",
      "Sarnath archaeological site where Lord Buddha gave his first sermon"
    ],
    "nearestHubs": { "airport": "Lal Bahadur Shastri Int Airport Varanasi VNS", "railway": "Varanasi Jn (BSB) / Banaras (BSBS)", "road": "NH-19 / Purvanchal Expressway" },
    "transitSummary": "Direct flights to Varanasi (VNS) from Delhi, Mumbai, Bengaluru, Hyderabad. Direct Vande Bharat trains from Delhi (8 hours)."
  },
  {
    "id": "ayodhya",
    "name": "Ayodhya Ram Mandir",
    "state": "Uttar Pradesh",
    "region": "north",
    "tagline": "The Holy Janmabhoomi of Lord Shri Ram",
    "description": "The revered birthplace of Lord Rama on the banks of sacred River Saryu. Marvel at the grand Nagara-style Shri Ram Janmabhoomi Mandir, Hanuman Garhi, and evening Saryu Aarti.",
    "elevation": "93 m (305 ft)",
    "bestTime": "Oct to Mar",
    "idealDays": "2 Days",
    "category": "sacred",
    "mood": ["Spiritual", "Heritage", "Peace"],
    "basePriceINR": 2200,
    "rating": 4.9,
    "reviewsCount": 650,
    "heroImage": "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Ram Mandir", "Hanuman Garhi", "Saryu Ghat", "Kanak Bhawan"],
    "highlights": [
      "Darshan at the monumental pink sandstone Shri Ram Janmabhoomi Mandir",
      "Climb 76 steps to historic 10th-century Hanuman Garhi temple",
      "Evening musical Saryu River Maha Aarti at Ram Ki Paidi",
      "Kanak Bhawan palace temple gifted to Goddess Sita"
    ],
    "nearestHubs": { "airport": "Maharishi Valmiki International Airport Ayodhya AY", "railway": "Ayodhya Dham Jn (AY) / Ayodhya Cantt", "road": "Lucknow-Ayodhya-Gorakhpur 4-lane NH-27" },
    "transitSummary": "Direct flights to Ayodhya (AY) from Delhi, Mumbai, Bengaluru, Ahmedabad. 2.5-hour drive from Lucknow (130 km) via NH-27."
  },
  {
    "id": "agra",
    "name": "Agra Taj Mahal",
    "state": "Uttar Pradesh",
    "region": "north",
    "tagline": "Wonder of the World & Mughal Imperial Capital",
    "description": "Home to the immortal white marble mausoleum Taj Mahal — UNESCO World Heritage Wonder of the World — alongside the massive red sandstone Agra Fort and Fatehpur Sikri.",
    "elevation": "171 m (561 ft)",
    "bestTime": "Oct to Mar",
    "idealDays": "2 Days",
    "category": "heritage",
    "mood": ["Heritage", "Wonder", "Romantic"],
    "basePriceINR": 2600,
    "rating": 4.9,
    "reviewsCount": 780,
    "heroImage": "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Taj Mahal", "Agra Fort", "Fatehpur Sikri", "Mehtab Bagh"],
    "highlights": [
      "Sunrise view of the Taj Mahal reflecting in the marble lotus pond",
      "Agra Fort palaces and Musamman Burj where Shah Jahan was imprisoned",
      "Fatehpur Sikri imperial ghost city & Buland Darwaza",
      "Mehtab Bagh sunset view across the Yamuna River"
    ],
    "nearestHubs": { "airport": "Agra Airport AGR / Delhi IGI (200 km)", "railway": "Agra Cantt AGC", "road": "Yamuna Expressway (165 km from Delhi)" },
    "transitSummary": "1.5-hour train ride from Delhi via Gatimaan / Vande Bharat Express. 2.5-hour drive from Delhi on 6-lane Yamuna Expressway."
  },
  {
    "id": "ujjain",
    "name": "Ujjain Mahakal",
    "state": "Madhya Pradesh",
    "region": "central",
    "tagline": "Mahakaleshwar Jyotirlinga, Bhasma Aarti & Mahakal Lok",
    "description": "One of India's seven holy Moksha puris on the Shipra River. Famous for the south-facing Dakshinmukhi Mahakaleshwar Jyotirlinga, mystical 4 AM Bhasma Aarti, and grand Mahakal Lok corridor.",
    "elevation": "491 m (1,610 ft)",
    "bestTime": "Oct to Mar",
    "idealDays": "2 Days",
    "category": "sacred",
    "mood": ["Spiritual", "Heritage", "Peace"],
    "basePriceINR": 2400,
    "rating": 4.9,
    "reviewsCount": 540,
    "heroImage": "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Mahakaleshwar", "Bhasma Aarti", "Mahakal Lok", "Shipra River"],
    "highlights": [
      "Witness sacred 4:00 AM Bhasma Aarti performed with sacred ash",
      "Grand 900-meter Mahakal Lok corridor with 108 ornate stone pillars",
      "Kal Bhairav Temple where liquor is offered as prasad",
      "Holy dip at Ram Ghat during evening Shipra Aarti"
    ],
    "nearestHubs": { "airport": "Devi Ahilyabai Holkar Airport Indore IDR (55 km)", "railway": "Ujjain Junction UJN", "road": "Indore-Ujjain 4-Lane Expressway" },
    "transitSummary": "55 km (1 hour) from Indore International Airport (IDR) via 4-lane expressway. Direct trains from Mumbai, Delhi, and Jaipur."
  },
  {
    "id": "rann-of-kutch",
    "name": "Rann of Kutch",
    "state": "Gujarat",
    "region": "west",
    "tagline": "The Great White Salt Desert & Rann Utsav",
    "description": "World's largest white salt marsh desert! During full moon nights, the salt crystals glisten like silver under the sky. Celebrate with luxury tent cities, camel safaris, and Kutchi handicrafts.",
    "elevation": "Sea Level",
    "bestTime": "Nov to Feb (Rann Utsav)",
    "idealDays": "3 - 4 Days",
    "category": "heritage",
    "mood": ["Desert", "Festivals", "Offbeat"],
    "basePriceINR": 4200,
    "rating": 4.9,
    "reviewsCount": 390,
    "heroImage": "https://images.unsplash.com/photo-1577717903315-1691ae25ab3f?auto=format&fit=crop&w=1200&q=80",
    "tags": ["White Desert", "Rann Utsav", "Dhordo Tent City", "Kala Dungar"],
    "highlights": [
      "Walk on the endless white salt desert under the glowing Full Moon",
      "Kala Dungar (Black Hill) highest point with panoramic desert view",
      "Traditional Rogan art and mirror-work embroidery in Nirona artisan village",
      "Kutch Fossil Park and Dholavira Harappan UNESCO site"
    ],
    "nearestHubs": { "airport": "Bhuj Airport BHJ (80 km)", "railway": "Bhuj BHUJ", "road": "Bhuj-Dhordo Highway" },
    "transitSummary": "80 km from Bhuj Airport / Railway station. Regular AC coaches and taxis operate directly to Dhordo Tent City."
  },

  # --- 8. NORTHEAST, SIKKIM & ISLANDS ---
  {
    "id": "darjeeling",
    "name": "Darjeeling",
    "state": "West Bengal",
    "region": "east",
    "tagline": "Queen of the Hills, Kanchenjunga & Heritage Toy Train",
    "description": "Perched amidst rolling tea estates overlooking the majestic snow peaks of Mount Kanchenjunga (8,586 m). Ride the UNESCO Darjeeling Himalayan Railway and watch golden sunrises from Tiger Hill.",
    "elevation": "2,042 m (6,700 ft)",
    "bestTime": "Mar to May & Oct to Dec",
    "idealDays": "3 - 4 Days",
    "category": "mountains",
    "mood": ["Tea Hills", "Heritage", "Romantic"],
    "basePriceINR": 3200,
    "rating": 4.8,
    "reviewsCount": 460,
    "heroImage": "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Tiger Hill", "Toy Train", "Kanchenjunga", "Tea Estates"],
    "highlights": [
      "4:00 AM Tiger Hill sunrise illuminating Mount Kanchenjunga and Everest",
      "UNESCO steam Toy Train joyride through Batasia Loop",
      "Happy Valley Tea Estate premium Muscatel tea tasting",
      "Himalayan Mountaineering Institute & Snow Leopard zoo"
    ],
    "nearestHubs": { "airport": "Bagdogra Airport IXB (70 km)", "railway": "New Jalpaiguri NJP (75 km)", "road": "NH-110 Hill Cart Road" },
    "transitSummary": "70 km (3 hours) from Bagdogra Airport (IXB) / New Jalpaiguri (NJP) via scenic Hill Cart Road."
  },
  {
    "id": "gangtok",
    "name": "Gangtok & Nathu La",
    "state": "Sikkim",
    "region": "northeast",
    "tagline": "Himalayan Silk Route, Monasteries & Tsomgo Lake",
    "description": "The pristine, clean mountain capital of Sikkim. Visit Rumtek Monastery, ride the ropeway over misty valleys, and drive to the Indo-China border at Nathu La Pass and glacial Tsomgo Lake.",
    "elevation": "1,650 m (5,410 ft)",
    "bestTime": "Mar to Jun & Sep to Dec",
    "idealDays": "4 - 5 Days",
    "category": "mountains",
    "mood": ["High Treks", "Heritage", "Snow"],
    "basePriceINR": 3500,
    "rating": 4.8,
    "reviewsCount": 420,
    "heroImage": "https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Nathu La Pass", "Tsomgo Lake", "Rumtek Monastery", "MG Marg"],
    "highlights": [
      "High-altitude glacial Tsomgo (Changu) Lake (12,310 ft) with yaks",
      "Nathu La Pass (14,140 ft) on the historic Old Silk Route to Tibet",
      "Rumtek 16th-century Tibetan monastery and gold stupas",
      "Vehicle-free, floral cobblestone MG Marg promenade"
    ],
    "nearestHubs": { "airport": "Pakyong Airport PYG (30 km) / Bagdogra IXB (120 km)", "railway": "New Jalpaiguri NJP (120 km)", "road": "NH-10 along Teesta River" },
    "transitSummary": "120 km (4.5 hours) from Bagdogra Airport (IXB) along scenic Teesta River. Inner Line Permit (ILP) easily arranged."
  },
  {
    "id": "shillong",
    "name": "Shillong & Cherrapunji",
    "state": "Meghalaya",
    "region": "northeast",
    "tagline": "Scotland of the East, Living Root Bridges & Waterfalls",
    "description": "The abode of clouds! Hike to the Double Decker Living Root Bridge in Nongriat, marvel at Nohkalikai Falls (India's tallest plunge waterfall), and boat on crystal transparent Dawki River.",
    "elevation": "1,525 m (5,000 ft)",
    "bestTime": "Sep to May",
    "idealDays": "4 - 5 Days",
    "category": "mountains",
    "mood": ["Waterfalls", "High Treks", "Nature"],
    "basePriceINR": 3400,
    "rating": 4.9,
    "reviewsCount": 480,
    "heroImage": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Living Root Bridge", "Nohkalikai Falls", "Dawki River", "Umiam Lake"],
    "highlights": [
      "Trek 3,500 stone steps down to the 250-year-old Double Decker Living Root Bridge",
      "Nohkalikai Falls (1,115 ft) plummeting into a turquoise pool",
      "Transparent glass-like Umngot river boating in Dawki",
      "Mawlynnong — officially awarded Cleanest Village in Asia"
    ],
    "nearestHubs": { "airport": "Shillong Airport SHL (30 km) / Guwahati GAU (120 km)", "railway": "Guwahati GHY (100 km)", "road": "Guwahati-Shillong 4-Lane Expressway (GS Road)" },
    "transitSummary": "100 km (3 hours) from Guwahati Airport/Station via smooth 4-lane highway through Umiam Lake."
  },
  {
    "id": "andaman",
    "name": "Andaman & Havelock Island",
    "state": "Andaman & Nicobar Islands",
    "region": "islands",
    "tagline": "Turquoise Coral Lagoons, Radhanagar Beach & Cellular Jail",
    "description": "An exotic tropical archipelago in the Bay of Bengal. Relax on Radhanagar Beach (voted Best in Asia), scuba dive amidst vibrant coral reefs, and experience the historic Cellular Jail.",
    "elevation": "Sea Level",
    "bestTime": "Oct to May",
    "idealDays": "5 - 7 Days",
    "category": "beaches",
    "mood": ["Beaches", "Diving", "Romantic"],
    "basePriceINR": 4800,
    "rating": 4.9,
    "reviewsCount": 510,
    "heroImage": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
    "tags": ["Radhanagar Beach", "Scuba Diving", "Cellular Jail", "Havelock Island"],
    "highlights": [
      "Sunset stroll on Radhanagar Beach (Beach No. 7) powdery white sands",
      "World-class scuba diving & sea-walking at Elephant Beach and Neil Island",
      "Cellular Jail national memorial Light & Sound show in Port Blair",
      "High-speed catamaran cruise across azure islands"
    ],
    "nearestHubs": { "airport": "Veer Savarkar International Airport Port Blair (IXZ)", "railway": "None (Island)", "road": "Andaman Trunk Road" },
    "transitSummary": "Direct flights from Chennai, Kolkata, Delhi, and Bengaluru to Port Blair (IXZ). High-speed catamarans (Makruzz/Nautika) connect Port Blair to Havelock & Neil Islands."
  }
]

code = """/**
 * RAAHIYOO 2.0 — Master Dataset of 50+ Famous Indian Destinations
 * Complete metadata covering all 28 states & union territories with GPS coordinates.
 */

const CURRENCIES = {
  INR: { symbol: "₹", rate: 1, label: "INR (₹)" },
  USD: { symbol: "$", rate: 0.012, label: "USD ($)" },
  EUR: { symbol: "€", rate: 0.011, label: "EUR (€)" },
  AED: { symbol: "AED ", rate: 0.044, label: "AED (د.إ)" }
};

const DESTINATIONS = """ + json.dumps(destinations, indent=2) + """;

// Export / global attachment
if (typeof window !== 'undefined') {
  window.DESTINATIONS = DESTINATIONS;
  window.CURRENCIES = CURRENCIES;
}
"""

with open("/home/linuxlite/.gemini/antigravity/scratch/raahiyoo/js/data.js", "w") as f:
    f.write(code)

print("SUCCESS: Updated data.js written successfully!")
